## when to use Encoding
- One-Hot: Low/medium cardinality; tree models and linear models.
- Label: Ordinal categories or tree-based models (not linear without caution).
- Target: High-cardinality with strong target signal; risk of leakage.
- Count/Frequency: High-cardinality; compact representation; preserves prevalence.
- Binary: Very high-cardinality; reduces dimensionality vs one-hot.

In [13]:
# Setup: sample data
import pandas as pd
import numpy as np

df = pd.DataFrame({
    'city': ['NY','SF','LA','LA','NY','TX','TX','SF','SF','LA'],
    'device': ['mobile','desktop','tablet','mobile','desktop','mobile','tablet','desktop','mobile','tablet'],
    'tier': ['basic','pro','basic','plus','pro','basic','plus','basic','plus','pro'],
    'y': [1,0,1,0,1,0,1,0,0,1]
})
df

  city   device   tier  y
0   NY   mobile  basic  1
1   SF  desktop    pro  0
2   LA   tablet  basic  1
3   LA   mobile   plus  0
4   NY  desktop    pro  1
5   TX   mobile  basic  0
6   TX   tablet   plus  1
7   SF  desktop  basic  0
8   SF   mobile   plus  0
9   LA   tablet    pro  1

In [14]:
from sklearn.preprocessing import OneHotEncoder

In [15]:
ohe=OneHotEncoder()

In [18]:
ohe.fit_transform(df[['city','device']])

<Compressed Sparse Row sparse matrix of dtype 'float64'
	with 20 stored elements and shape (10, 7)>

In [22]:
pd.DataFrame(ohe.fit_transform(df[['city','device','tier']]),columns=ohe.get_feature_names_out(['city','device','tier']))

ValueError: Shape of passed values is (10, 1), indices imply (10, 10)

In [23]:
arr=['red','orange','red','orange']

In [27]:
ohe=OneHotEncoder(categories=['red','orange'])

In [29]:
ohe.fit(arr).reshape(-1,-1)

ValueError: Expected 2D array, got 1D array instead:
array=['red' 'orange' 'red' 'orange'].
Reshape your data either using array.reshape(-1, 1) if your data has a single feature or array.reshape(1, -1) if it contains a single sample.

In [30]:
from sklearn.preprocessing import LabelEncoder

In [31]:

df = pd.DataFrame({
    'city': ['NY','SF','LA','LA','NY','TX','TX','SF','SF','LA'],
    'device': ['mobile','desktop','tablet','mobile','desktop','mobile','tablet','desktop','mobile','tablet'],
    'tier': ['basic','pro','basic','plus','pro','basic','plus','basic','plus','pro'],
    'y': [1,0,1,0,1,0,1,0,0,1]
})
df

  city   device   tier  y
0   NY   mobile  basic  1
1   SF  desktop    pro  0
2   LA   tablet  basic  1
3   LA   mobile   plus  0
4   NY  desktop    pro  1
5   TX   mobile  basic  0
6   TX   tablet   plus  1
7   SF  desktop  basic  0
8   SF   mobile   plus  0
9   LA   tablet    pro  1

In [33]:
le=LabelEncoder()
df['city_encoded']=le.fit_transform(df.city)

In [35]:
df[['city','city_encoded']]

  city  city_encoded
0   NY             1
1   SF             2
2   LA             0
3   LA             0
4   NY             1
5   TX             3
6   TX             3
7   SF             2
8   SF             2
9   LA             0

In [36]:
df

  city   device   tier  y  city_encoded
0   NY   mobile  basic  1             1
1   SF  desktop    pro  0             2
2   LA   tablet  basic  1             0
3   LA   mobile   plus  0             0
4   NY  desktop    pro  1             1
5   TX   mobile  basic  0             3
6   TX   tablet   plus  1             3
7   SF  desktop  basic  0             2
8   SF   mobile   plus  0             2
9   LA   tablet    pro  1             0

In [38]:
df['device'].value_counts(normalize=True)

device
mobile     0.4
desktop    0.3
tablet     0.3
Name: proportion, dtype: float64

In [39]:
df['device_freq']=df['device'].map(df['device'].value_counts(normalize=True))

In [40]:
df

  city   device   tier  y  city_encoded  device_freq
0   NY   mobile  basic  1             1          0.4
1   SF  desktop    pro  0             2          0.3
2   LA   tablet  basic  1             0          0.3
3   LA   mobile   plus  0             0          0.4
4   NY  desktop    pro  1             1          0.3
5   TX   mobile  basic  0             3          0.4
6   TX   tablet   plus  1             3          0.3
7   SF  desktop  basic  0             2          0.3
8   SF   mobile   plus  0             2          0.4
9   LA   tablet    pro  1             0          0.3