In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [2]:
df=pd.read_csv('data.csv')

In [3]:
df.head()

,customer_id,name,gender,education_level,employment_status,city,product_category,satisfaction_rating,subscription_tier,payment_method,...,purchase_frequency,customer_segment,income_bracket,age_group,membership_status,preferred_language,region,season_joined,credit_rating,target_purchased
0,1,Alice Johnson,Female,Bachelor,Full-time,Mumbai,Electronics,Very Satisfied,Premium,Credit Card,...,Weekly,High Value,High,Adult,Gold,English,West,Summer,Excellent,Yes
1,2,Bob Smith,Male,Master,Self-employed,Delhi,Clothing,Satisfied,Standard,Debit Card,...,Monthly,Medium Value,Medium,Senior,Silver,Hindi,North,Winter,Good,Yes
2,3,Charlie Brown,Male,High School,Unemployed,Bangalore,Home & Kitchen,Neutral,Basic,Cash,...,Rarely,Low Value,Low,Young Adult,Bronze,English,South,Spring,Fair,No
3,4,Diana Prince,Female,PhD,Full-time,Hyderabad,Beauty,Very Satisfied,Premium,UPI,...,Daily,High Value,Very High,Adult,Platinum,Telugu,South,Autumn,Excellent,Yes
4,5,Edward Lee,Male,Bachelor,Part-time,Chennai,Sports,Satisfied,Standard,Credit Card,...,Weekly,Medium Value,Medium,Adult,Gold,Tamil,South,Summer,Good,Yes

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 50 entries, 0 to 49
Data columns (total 21 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   customer_id          50 non-null     int64
 1   name                 50 non-null     object
 2   gender               50 non-null     object
 3   education_level      50 non-null     object
 4   employment_status    50 non-null     object
 5   city                 50 non-null     object
 6   product_category     50 non-null     object
 7   satisfaction_rating  50 non-null     object
 8   subscription_tier    50 non-null     object
 9   payment_method       50 non-null     object
 10  device_type          50 non-null     object
 11  purchase_frequency   50 non-null     object
 12  customer_segment     50 non-null     object
 13  income_bracket       50 non-null     object
 14  age_group            50 non-null     object
 15  membership_status    50 non-null     object
 16  preferred_language   50 non-null     object
 17  region               50 non-null     object
 18  season_joined        50 non-null     object
 19  credit_rating        50 non-null     object
 20  target_purchased     50 non-null     object
dtypes: int64(1), object(20)
memory usage: 8.3+ KB

In [5]:
df.describe()

       customer_id
count     50.00000
mean      25.50000
std       14.57738
min        1.00000
25%       13.25000
50%       25.50000
75%       37.75000
max       50.00000

In [6]:
df.head()

,customer_id,name,gender,education_level,employment_status,city,product_category,satisfaction_rating,subscription_tier,payment_method,...,purchase_frequency,customer_segment,income_bracket,age_group,membership_status,preferred_language,region,season_joined,credit_rating,target_purchased
0,1,Alice Johnson,Female,Bachelor,Full-time,Mumbai,Electronics,Very Satisfied,Premium,Credit Card,...,Weekly,High Value,High,Adult,Gold,English,West,Summer,Excellent,Yes
1,2,Bob Smith,Male,Master,Self-employed,Delhi,Clothing,Satisfied,Standard,Debit Card,...,Monthly,Medium Value,Medium,Senior,Silver,Hindi,North,Winter,Good,Yes
2,3,Charlie Brown,Male,High School,Unemployed,Bangalore,Home & Kitchen,Neutral,Basic,Cash,...,Rarely,Low Value,Low,Young Adult,Bronze,English,South,Spring,Fair,No
3,4,Diana Prince,Female,PhD,Full-time,Hyderabad,Beauty,Very Satisfied,Premium,UPI,...,Daily,High Value,Very High,Adult,Platinum,Telugu,South,Autumn,Excellent,Yes
4,5,Edward Lee,Male,Bachelor,Part-time,Chennai,Sports,Satisfied,Standard,Credit Card,...,Weekly,Medium Value,Medium,Adult,Gold,Tamil,South,Summer,Good,Yes

In [7]:
df_copy=df.copy()

In [8]:
df_copy.drop(['name','customer_id'],axis=1,inplace=True)

In [9]:
df_copy.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 50 entries, 0 to 49
Data columns (total 19 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   gender               50 non-null     object
 1   education_level      50 non-null     object
 2   employment_status    50 non-null     object
 3   city                 50 non-null     object
 4   product_category     50 non-null     object
 5   satisfaction_rating  50 non-null     object
 6   subscription_tier    50 non-null     object
 7   payment_method       50 non-null     object
 8   device_type          50 non-null     object
 9   purchase_frequency   50 non-null     object
 10  customer_segment     50 non-null     object
 11  income_bracket       50 non-null     object
 12  age_group            50 non-null     object
 13  membership_status    50 non-null     object
 14  preferred_language   50 non-null     object
 15  region               50 non-null     object
 16  season_joined        50 non-null     object
 17  credit_rating        50 non-null     object
 18  target_purchased     50 non-null     object
dtypes: object(19)
memory usage: 7.5+ KB

In [10]:
df.gender.unique()

array(['Female', 'Male'], dtype=object)

In [11]:
from sklearn.preprocessing import OneHotEncoder

In [12]:
ohe=OneHotEncoder(sparse_output=False)

In [13]:
ohe1=OneHotEncoder()
np.array(ohe.fit_transform(df[['gender']]))

array([[1., 0.],
       [0., 1.],
       [0., 1.],
       [1., 0.],
       [0., 1.],
       [1., 0.],
       [0., 1.],
       [1., 0.],
       [0., 1.],
       [1., 0.],
       [0., 1.],
       [1., 0.],
       [0., 1.],
       [1., 0.],
       [0., 1.],
       [1., 0.],
       [0., 1.],
       [1., 0.],
       [0., 1.],
       [1., 0.],
       [1., 0.],
       [0., 1.],
       [1., 0.],
       [0., 1.],
       [1., 0.],
       [0., 1.],
       [1., 0.],
       [0., 1.],
       [1., 0.],
       [0., 1.],
       [1., 0.],
       [0., 1.],
       [1., 0.],
       [0., 1.],
       [1., 0.],
       [0., 1.],
       [1., 0.],
       [0., 1.],
       [1., 0.],
       [0., 1.],
       [1., 0.],
       [0., 1.],
       [1., 0.],
       [1., 0.],
       [0., 1.],
       [1., 0.],
       [0., 1.],
       [1., 0.],
       [0., 1.],
       [1., 0.]])

In [14]:
ohe.fit_transform(df[['gender']])

array([[1., 0.],
       [0., 1.],
       [0., 1.],
       [1., 0.],
       [0., 1.],
       [1., 0.],
       [0., 1.],
       [1., 0.],
       [0., 1.],
       [1., 0.],
       [0., 1.],
       [1., 0.],
       [0., 1.],
       [1., 0.],
       [0., 1.],
       [1., 0.],
       [0., 1.],
       [1., 0.],
       [0., 1.],
       [1., 0.],
       [1., 0.],
       [0., 1.],
       [1., 0.],
       [0., 1.],
       [1., 0.],
       [0., 1.],
       [1., 0.],
       [0., 1.],
       [1., 0.],
       [0., 1.],
       [1., 0.],
       [0., 1.],
       [1., 0.],
       [0., 1.],
       [1., 0.],
       [0., 1.],
       [1., 0.],
       [0., 1.],
       [1., 0.],
       [0., 1.],
       [1., 0.],
       [0., 1.],
       [1., 0.],
       [1., 0.],
       [0., 1.],
       [1., 0.],
       [0., 1.],
       [1., 0.],
       [0., 1.],
       [1., 0.]])

In [15]:
gender_columns=pd.DataFrame(ohe.fit_transform(df[['gender']]),columns=ohe.get_feature_names_out())

In [16]:
df_copy.head()

,gender,education_level,employment_status,city,product_category,satisfaction_rating,subscription_tier,payment_method,device_type,purchase_frequency,customer_segment,income_bracket,age_group,membership_status,preferred_language,region,season_joined,credit_rating,target_purchased
0,Female,Bachelor,Full-time,Mumbai,Electronics,Very Satisfied,Premium,Credit Card,Mobile,Weekly,High Value,High,Adult,Gold,English,West,Summer,Excellent,Yes
1,Male,Master,Self-employed,Delhi,Clothing,Satisfied,Standard,Debit Card,Desktop,Monthly,Medium Value,Medium,Senior,Silver,Hindi,North,Winter,Good,Yes
2,Male,High School,Unemployed,Bangalore,Home & Kitchen,Neutral,Basic,Cash,Tablet,Rarely,Low Value,Low,Young Adult,Bronze,English,South,Spring,Fair,No
3,Female,PhD,Full-time,Hyderabad,Beauty,Very Satisfied,Premium,UPI,Mobile,Daily,High Value,Very High,Adult,Platinum,Telugu,South,Autumn,Excellent,Yes
4,Male,Bachelor,Part-time,Chennai,Sports,Satisfied,Standard,Credit Card,Laptop,Weekly,Medium Value,Medium,Adult,Gold,Tamil,South,Summer,Good,Yes

In [17]:
df_copy.drop('gender',inplace=True,axis=1)

In [18]:
df_copy

,education_level,employment_status,city,product_category,satisfaction_rating,subscription_tier,payment_method,device_type,purchase_frequency,customer_segment,income_bracket,age_group,membership_status,preferred_language,region,season_joined,credit_rating,target_purchased
0,Bachelor,Full-time,Mumbai,Electronics,Very Satisfied,Premium,Credit Card,Mobile,Weekly,High Value,High,Adult,Gold,English,West,Summer,Excellent,Yes
1,Master,Self-employed,Delhi,Clothing,Satisfied,Standard,Debit Card,Desktop,Monthly,Medium Value,Medium,Senior,Silver,Hindi,North,Winter,Good,Yes
2,High School,Unemployed,Bangalore,Home & Kitchen,Neutral,Basic,Cash,Tablet,Rarely,Low Value,Low,Young Adult,Bronze,English,South,Spring,Fair,No
3,PhD,Full-time,Hyderabad,Beauty,Very Satisfied,Premium,UPI,Mobile,Daily,High Value,Very High,Adult,Platinum,Telugu,South,Autumn,Excellent,Yes
4,Bachelor,Part-time,Chennai,Sports,Satisfied,Standard,Credit Card,Laptop,Weekly,Medium Value,Medium,Adult,Gold,Tamil,South,Summer,Good,Yes
5,High School,Student,Kolkata,Books,Dissatisfied,Basic,Debit Card,Mobile,Monthly,Low Value,Low,Young Adult,Bronze,Bengali,East,Winter,Fair,No
6,Master,Full-time,Pune,Electronics,Very Satisfied,Premium,Credit Card,Desktop,Weekly,High Value,High,Senior,Platinum,English,West,Spring,Excellent,Yes
7,Bachelor,Full-time,Ahmedabad,Clothing,Satisfied,Standard,UPI,Mobile,Bi-weekly,Medium Value,Medium,Adult,Silver,Gujarati,West,Autumn,Good,Yes
8,Associate,Unemployed,Jaipur,Home & Kitchen,Neutral,Basic,Cash,Tablet,Rarely,Low Value,Low,Adult,Bronze,Hindi,North,Summer,Fair,No
9,PhD,Full-time,Surat,Beauty,Very Satisfied,Premium,Credit Card,Laptop,Daily,High Value,Very High,Senior,Platinum,Gujarati,West,Winter,Excellent,Yes
10,High School,Part-time,Lucknow,Sports,Dissatisfied,Basic,Debit Card,Mobile,Monthly,Low Value,Low,Young Adult,Bronze,Hindi,North,Spring,Poor,No
11,Bachelor,Full-time,Kanpur,Books,Satisfied,Standard,UPI,Desktop,Weekly,Medium Value,Medium,Adult,Gold,Hindi,North,Autumn,Good,Yes
12,Master,Self-employed,Nagpur,Electronics,Very Satisfied,Premium,Credit Card,Mobile,Weekly,High Value,High,Senior,Platinum,Marathi,Central,Summer,Excellent,Yes
13,Associate,Full-time,Indore,Clothing,Satisfied,Standard,Debit Card,Laptop,Bi-weekly,Medium Value,Medium,Adult,Silver,Hindi,Central,Winter,Good,Yes
14,PhD,Full-time,Thane,Home & Kitchen,Very Satisfied,Premium,UPI,Desktop,Weekly,High Value,Very High,Senior,Platinum,Marathi,West,Spring,Excellent,Yes
15,High School,Unemployed,Bhopal,Beauty,Neutral,Basic,Cash,Mobile,Rarely,Low Value,Low,Young Adult,Bronze,Hindi,Central,Autumn,Fair,No
16,Bachelor,Part-time,Visakhapatnam,Sports,Satisfied,Standard,Credit Card,Tablet,Monthly,Medium Value,Medium,Adult,Gold,Telugu,South,Summer,Good,Yes
17,Master,Full-time,Patna,Books,Very Satisfied,Premium,Debit Card,Laptop,Weekly,High Value,High,Senior,Platinum,Hindi,East,Winter,Excellent,Yes
18,Associate,Self-employed,Vadodara,Electronics,Satisfied,Standard,UPI,Mobile,Bi-weekly,Medium Value,Medium,Adult,Silver,Gujarati,West,Spring,Good,Yes
19,High School,Student,Ghaziabad,Clothing,Dissatisfied,Basic,Cash,Desktop,Rarely,Low Value,Low,Young Adult,Bronze,Hindi,North,Autumn,Fair,No
20,PhD,Full-time,Ludhiana,Home & Kitchen,Very Satisfied,Premium,Credit Card,Mobile,Daily,High Value,Very High,Senior,Platinum,Punjabi,North,Summer,Excellent,Yes
21,High School,Unemployed,Agra,Beauty,Neutral,Basic,Debit Card,Tablet,Monthly,Low Value,Low,Young Adult,Bronze,Hindi,North,Winter,Poor,No
22,Bachelor,Full-time,Nashik,Sports,Satisfied,Standard,UPI,Laptop,Weekly,Medium Value,Medium,Adult,Gold,Marathi,West,Spring,Good,Yes
23,Master,Self-employed,Faridabad,Books,Very Satisfied,Premium,Credit Card,Desktop,Weekly,High Value,High,Senior,Platinum,Hindi,North,Autumn,Excellent,Yes
24,Associate,Part-time,Meerut,Electronics,Satisfied,Standard,Debit Card,Mobile,Bi-weekly,Medium Value,Medium,Adult,Silver,Hindi,North,Summer,Good,Yes
25,PhD,Full-time,Rajkot,Clothing,Very Satisfied,Premium,UPI,Laptop,Weekly,High Value,Very High,Senior,Platinum,Gujarati,West,Winter,Excellent,Yes
26,High School,Student,Kalyan,Home & Kitchen,Dissatisfied,Basic,Cash,Mobile,Rarely,Low Value,Low,Young Adult,Bronze,Marathi,West,Spring,Fair,No
27,Bachelor,Full-time,Vasai,Beauty,Satisfied,Standard,Credit Card,Desktop,Monthly,Medium Value,Medium,Adult,Gold,Marathi,West,Autumn,Good,Yes
28,Master,Full-time,Varanasi,Sports,Very Satisfied,Premium,Debit Card,Tablet,Weekly,High Value,High,Senior,Platinum,Hindi,North,Summer,Excellent,Yes
29,Associate,Unemployed,Srinagar,Books,Neutral,Basic,Cash,Mobile,Rarely,Low Value,Low,Adult,Bronze,Kashmiri,North,Winter,Fair,No
30,PhD,Full-time,Aurangabad,Electronics,Very Satisfied,Premium,UPI,Laptop,Daily,High Value,Very High,Senior,Platinum,Marathi,Central,Spring,Excellent,Yes
31,High School,Part-time,Dhanbad,Clothing,Dissatisfied,Basic,Debit Card,Mobile,Monthly,Low Value,Low,Young Adult,Bronze,Hindi,East,Autumn,Poor,No
32,Bachelor,Full-time,Amritsar,Home & Kitchen,Satisfied,Standard,Credit Card,Desktop,Weekly,Medium Value,Medium,Adult,Gold,Punjabi,North,Summer,Good,Yes
33,Master,Self-employed,Allahabad,Beauty,Very Satisfied,Premium,UPI,Mobile,Weekly,High Value,High,Senior,Platinum,Hindi,North,Winter,Excellent,Yes
34,Associate,Full-time,Ranchi,Sports,Satisfied,Standard,Debit Card,Laptop,Bi-weekly,Medium Value,Medium,Adult,Silver,Hindi,East,Spring,Good,Yes
35,Bachelor,Part-time,Howrah,Books,Satisfied,Standard,Cash,Tablet,Monthly,Medium Value,Medium,Adult,Gold,Bengali,East,Autumn,Good,Yes
36,PhD,Full-time,Coimbatore,Electronics,Very Satisfied,Premium,Credit Card,Desktop,Weekly,High Value,Very High,Senior,Platinum,Tamil,South,Summer,Excellent,Yes
37,High School,Unemployed,Jodhpur,Clothing,Neutral,Basic,Debit Card,Mobile,Rarely,Low Value,Low,Young Adult,Bronze,Hindi,North,Winter,Fair,No
38,Master,Full-time,Madurai,Home & Kitchen,Very Satisfied,Premium,UPI,Laptop,Weekly,High Value,High,Senior,Platinum,Tamil,South,Spring,Excellent,Yes
39,PhD,Self-employed,Gwalior,Beauty,Very Satisfied,Premium,Credit Card,Mobile,Daily,High Value,Very High,Senior,Platinum,Hindi,Central,Autumn,Excellent,Yes
40,High School,Student,Vijayawada,Sports,Dissatisfied,Basic,Debit Card,Desktop,Monthly,Low Value,Low,Young Adult,Bronze,Telugu,South,Summer,Fair,No
41,Bachelor,Full-time,Jabalpur,Books,Satisfied,Standard,UPI,Tablet,Weekly,Medium Value,Medium,Adult,Gold,Hindi,Central,Winter,Good,Yes
42,Associate,Part-time,Gurgaon,Electronics,Satisfied,Standard,Cash,Mobile,Bi-weekly,Medium Value,Medium,Adult,Silver,Hindi,North,Spring,Good,Yes
43,Master,Full-time,Mysore,Clothing,Very Satisfied,Premium,Credit Card,Laptop,Weekly,High Value,High,Senior,Platinum,Kannada,South,Autumn,Excellent,Yes
44,High School,Unemployed,Bareilly,Home & Kitchen,Neutral,Basic,Debit Card,Desktop,Rarely,Low Value,Low,Young Adult,Bronze,Hindi,North,Summer,Poor,No
45,Bachelor,Full-time,Aligarh,Beauty,Satisfied,Standard,UPI,Mobile,Monthly,Medium Value,Medium,Adult,Gold,Hindi,North,Winter,Good,Yes
46,PhD,Self-employed,Moradabad,Sports,Very Satisfied,Premium,Credit Card,Tablet,Weekly,High Value,Very High,Senior,Platinum,Hindi,North,Spring,Excellent,Yes
47,Associate,Full-time,Kota,Books,Satisfied,Standard,Debit Card,Laptop,Bi-weekly,Medium Value,Medium,Adult,Silver,Hindi,North,Autumn,Good,Yes
48,Master,Full-time,Bhubaneswar,Electronics,Very Satisfied,Premium,UPI,Desktop,Weekly,High Value,High,Senior,Platinum,Odia,East,Summer,Excellent,Yes
49,High School,Student,Chandigarh,Clothing,Dissatisfied,Basic,Cash,Mobile,Rarely,Low Value,Low,Young Adult,Bronze,Hindi,North,Winter,Fair,No

In [19]:
df_copy=pd.concat([df_copy,gender_columns],axis=1)

In [20]:
df_copy.head()

,education_level,employment_status,city,product_category,satisfaction_rating,subscription_tier,payment_method,device_type,purchase_frequency,customer_segment,income_bracket,age_group,membership_status,preferred_language,region,season_joined,credit_rating,target_purchased,gender_Female,gender_Male
0,Bachelor,Full-time,Mumbai,Electronics,Very Satisfied,Premium,Credit Card,Mobile,Weekly,High Value,High,Adult,Gold,English,West,Summer,Excellent,Yes,1.0,0.0
1,Master,Self-employed,Delhi,Clothing,Satisfied,Standard,Debit Card,Desktop,Monthly,Medium Value,Medium,Senior,Silver,Hindi,North,Winter,Good,Yes,0.0,1.0
2,High School,Unemployed,Bangalore,Home & Kitchen,Neutral,Basic,Cash,Tablet,Rarely,Low Value,Low,Young Adult,Bronze,English,South,Spring,Fair,No,0.0,1.0
3,PhD,Full-time,Hyderabad,Beauty,Very Satisfied,Premium,UPI,Mobile,Daily,High Value,Very High,Adult,Platinum,Telugu,South,Autumn,Excellent,Yes,1.0,0.0
4,Bachelor,Part-time,Chennai,Sports,Satisfied,Standard,Credit Card,Laptop,Weekly,Medium Value,Medium,Adult,Gold,Tamil,South,Summer,Good,Yes,0.0,1.0

In [21]:
df.education_level.unique()

array(['Bachelor', 'Master', 'High School', 'PhD', 'Associate'],
      dtype=object)

In [22]:
mapper={'Associate':5,"PhD":4,'Master':3,"Bachelor":2,"High School":1}

In [23]:
df_copy['education_level']=df_copy['education_level'].map(mapper)

In [24]:
type(df_copy)

pandas.core.frame.DataFrame

In [25]:
type(df.membership_status.unique())

numpy.ndarray

In [26]:
from sklearn.preprocessing import OrdinalEncoder

In [27]:
type(df_copy['education_level'].map(mapper))

pandas.core.series.Series

In [28]:
age=[1,2,3]

In [29]:
arr.append(10)

NameError: name 'arr' is not defined

In [ ]:
arr

In [ ]:
t=(1,2,3)

In [ ]:
t.append(10)

In [30]:
df_copy.membership_status.unique()

array(['Gold', 'Silver', 'Bronze', 'Platinum'], dtype=object)

In [31]:
oe=OrdinalEncoder(categories=[['Bronze','Silver','Gold','Platinum']])

In [32]:
df_copy['Membership_Status']=oe.fit_transform(df[['membership_status']])

In [33]:
df[['Membership_Status','membership_status']]

KeyError: "['Membership_Status'] not in index"

In [ ]:
df_copy.drop('membership_status',axis=1,inplace=True)

In [ ]:
df.Membership_Status.copy()

In [ ]:
df_copy['membership_status']=df.Membership_Status.copy()

In [ ]:
df_copy

In [ ]:
df

In [34]:
df_copy.city

0            Mumbai
1             Delhi
2         Bangalore
3         Hyderabad
4           Chennai
5           Kolkata
6              Pune
7         Ahmedabad
8            Jaipur
9             Surat
10          Lucknow
11           Kanpur
12           Nagpur
13           Indore
14            Thane
15           Bhopal
16    Visakhapatnam
17            Patna
18         Vadodara
19        Ghaziabad
20         Ludhiana
21             Agra
22           Nashik
23        Faridabad
24           Meerut
25           Rajkot
26           Kalyan
27            Vasai
28         Varanasi
29         Srinagar
30       Aurangabad
31          Dhanbad
32         Amritsar
33        Allahabad
34           Ranchi
35           Howrah
36       Coimbatore
37          Jodhpur
38          Madurai
39          Gwalior
40       Vijayawada
41         Jabalpur
42          Gurgaon
43           Mysore
44         Bareilly
45          Aligarh
46        Moradabad
47             Kota
48      Bhubaneswar
49       Chandigarh
Name: city, dtype: object

In [37]:
len(df_copy.city.unique())

50

In [38]:
from sklearn.preprocessing import LabelEncoder

In [39]:
le=LabelEncoder()

In [40]:
le.fit_transform(df.city)

array([34, 13,  6, 20, 11, 27, 39,  1, 23, 43, 29, 26, 36, 21, 44,  8, 49,
       38, 45, 16, 30,  0, 37, 15, 32, 40, 25, 47, 46, 42,  5, 14,  4,  3,
       41, 19, 12, 24, 31, 18, 48, 22, 17, 35,  7,  2, 33, 28,  9, 10])

In [41]:
!pip install category_encoders

Collecting category_encoders
  Downloading category_encoders-2.9.0-py3-none-any.whl.metadata (7.9 kB)
Requirement already satisfied: numpy>=1.14.0 in c:\users\krivi\appdata\local\programs\python\python311\lib\site-packages (from category_encoders) (2.3.5)
Requirement already satisfied: pandas>=1.0.5 in c:\users\krivi\appdata\local\programs\python\python311\lib\site-packages (from category_encoders) (2.3.3)
Collecting patsy>=0.5.1 (from category_encoders)
  Downloading patsy-1.0.2-py2.py3-none-any.whl.metadata (3.6 kB)
Requirement already satisfied: scikit-learn>=1.6.0 in c:\users\krivi\appdata\local\programs\python\python311\lib\site-packages (from category_encoders) (1.7.2)
Requirement already satisfied: scipy>=1.0.0 in c:\users\krivi\appdata\local\programs\python\python311\lib\site-packages (from category_encoders) (1.16.3)
Collecting statsmodels>=0.9.0 (from category_encoders)
  Downloading statsmodels-0.14.6-cp311-cp311-win_amd64.whl.metadata (9.8 kB)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\users\krivi\appdata\local\programs\python\python311\lib\site-packages (from pandas>=1.0.5->category_encoders) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in c:\users\krivi\appdata\local\programs\python\python311\lib\site-packages (from pandas>=1.0.5->category_encoders) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in c:\users\krivi\appdata\local\programs\python\python311\lib\site-packages (from pandas>=1.0.5->category_encoders) (2025.2)
Requirement already satisfied: six>=1.5 in c:\users\krivi\appdata\local\programs\python\python311\lib\site-packages (from python-dateutil>=2.8.2->pandas>=1.0.5->category_encoders) (1.17.0)
Requirement already satisfied: joblib>=1.2.0 in c:\users\krivi\appdata\local\programs\python\python311\lib\site-packages (from scikit-learn>=1.6.0->category_encoders) (1.5.2)
Requirement already satisfied: threadpoolctl>=3.1.0 in c:\users\krivi\appdata\local\programs\python\python311\lib\site-packages (from scikit-learn>=1.6.0->category_encoders) (3.6.0)
Requirement already satisfied: packaging>=21.3 in c:\users\krivi\appdata\local\programs\python\python311\lib\site-packages (from statsmodels>=0.9.0->category_encoders) (25.0)
Downloading category_encoders-2.9.0-py3-none-any.whl (85 kB)
Downloading patsy-1.0.2-py2.py3-none-any.whl (233 kB)
Downloading statsmodels-0.14.6-cp311-cp311-win_amd64.whl (9.6 MB)
   ---------------------------------------- 0.0/9.6 MB ? eta -:--:--
   --------------- ------------------------ 3.7/9.6 MB 21.8 MB/s eta 0:00:01
   ----------------- ---------------------- 4.2/9.6 MB 14.8 MB/s eta 0:00:01
   -------------------- ------------------- 5.0/9.6 MB 8.2 MB/s eta 0:00:01
   ------------------------- -------------- 6.0/9.6 MB 7.4 MB/s eta 0:00:01
   ----------------------------- ---------- 7.1/9.6 MB 6.9 MB/s eta 0:00:01
   --------------------------------- ------ 8.1/9.6 MB 6.8 MB/s eta 0:00:01
   -------------------------------------- - 9.2/9.6 MB 6.5 MB/s eta 0:00:01
   ---------------------------------------- 9.6/9.6 MB 6.2 MB/s  0:00:01
Installing collected packages: patsy, statsmodels, category_encoders

   ---------------------------------------- 0/3 [patsy]
   ---------------------------------------- 0/3 [patsy]
   ---------------------------------------- 0/3 [patsy]
   ---------------------------------------- 0/3 [patsy]
   ---------------------------------------- 0/3 [patsy]
   ---------------------------------------- 0/3 [patsy]
   ---------------------------------------- 0/3 [patsy]
   ------------- -------------------------- 1/3 [statsmodels]
   ------------- -------------------------- 1/3 [statsmodels]
   ------------- -------------------------- 1/3 [statsmodels]
   ------------- -------------------------- 1/3 [statsmodels]
   ------------- -------------------------- 1/3 [statsmodels]
   ------------- -------------------------- 1/3 [statsmodels]
   ------------- -------------------------- 1/3 [statsmodels]
   ------------- -------------------------- 1/3 [statsmodels]
   ------------- -------------------------- 1/3 [statsmodels]
   ------------- -------------------------- 1/3 [statsmodels]
   ------------- -------------------------- 1/3 [statsmodels]
   ------------- -------------------------- 1/3 [statsmodels]
   ------------- -------------------------- 1/3 [statsmodels]
   ------------- -------------------------- 1/3 [statsmodels]
   ------------- -------------------------- 1/3 [statsmodels]
   ------------- -------------------------- 1/3 [statsmodels]
   ------------- -------------------------- 1/3 [statsmodels]
   ------------- -------------------------- 1/3 [statsmodels]
   ------------- -------------------------- 1/3 [statsmodels]
   ------------- -------------------------- 1/3 [statsmodels]
   ------------- -------------------------- 1/3 [statsmodels]
   ------------- -------------------------- 1/3 [statsmodels]
   ------------- -------------------------- 1/3 [statsmodels]
   ------------- -------------------------- 1/3 [statsmodels]
   ------------- -------------------------- 1/3 [statsmodels]
   ------------- -------------------------- 1/3 [statsmodels]
   ------------- -------------------------- 1/3 [statsmodels]
   ------------- -------------------------- 1/3 [statsmodels]
   ------------- -------------------------- 1/3 [statsmodels]
   ------------- -------------------------- 1/3 [statsmodels]
   ------------- -------------------------- 1/3 [statsmodels]
   ------------- -------------------------- 1/3 [statsmodels]
   ------------- -------------------------- 1/3 [statsmodels]
   ------------- -------------------------- 1/3 [statsmodels]
   ------------- -------------------------- 1/3 [statsmodels]
   ------------- -------------------------- 1/3 [statsmodels]
   ------------- -------------------------- 1/3 [statsmodels]
   ------------- -------------------------- 1/3 [statsmodels]
   ------------- -------------------------- 1/3 [statsmodels]
   ------------- -------------------------- 1/3 [statsmodels]
   ------------- -------------------------- 1/3 [statsmodels]
   ------------- -------------------------- 1/3 [statsmodels]
   ------------- -------------------------- 1/3 [statsmodels]
   ------------- -------------------------- 1/3 [statsmodels]
   ------------- -------------------------- 1/3 [statsmodels]
   ------------- -------------------------- 1/3 [statsmodels]
   ------------- -------------------------- 1/3 [statsmodels]
   ------------- -------------------------- 1/3 [statsmodels]
   ------------- -------------------------- 1/3 [statsmodels]
   ------------- -------------------------- 1/3 [statsmodels]
   ------------- -------------------------- 1/3 [statsmodels]
   ------------- -------------------------- 1/3 [statsmodels]
   ------------- -------------------------- 1/3 [statsmodels]
   ------------- -------------------------- 1/3 [statsmodels]
   ------------- -------------------------- 1/3 [statsmodels]
   ------------- -------------------------- 1/3 [statsmodels]
   ------------- -------------------------- 1/3 [statsmodels]
   ------------- -------------------------- 1/3 [statsmodels]
   ------------- -------------------------- 1/3 [statsmodels]
   ------------- -------------------------- 1/3 [statsmodels]
   ------------- -------------------------- 1/3 [statsmodels]
   ------------- -------------------------- 1/3 [statsmodels]
   ------------- -------------------------- 1/3 [statsmodels]
   ------------- -------------------------- 1/3 [statsmodels]
   ------------- -------------------------- 1/3 [statsmodels]
   ------------- -------------------------- 1/3 [statsmodels]
   ------------- -------------------------- 1/3 [statsmodels]
   ------------- -------------------------- 1/3 [statsmodels]
   ------------- -------------------------- 1/3 [statsmodels]
   ------------- -------------------------- 1/3 [statsmodels]
   ------------- -------------------------- 1/3 [statsmodels]
   ------------- -------------------------- 1/3 [statsmodels]
   ------------- -------------------------- 1/3 [statsmodels]
   ------------- -------------------------- 1/3 [statsmodels]
   ------------- -------------------------- 1/3 [statsmodels]
   ------------- -------------------------- 1/3 [statsmodels]
   ------------- -------------------------- 1/3 [statsmodels]
   ------------- -------------------------- 1/3 [statsmodels]
   ------------- -------------------------- 1/3 [statsmodels]
   ------------- -------------------------- 1/3 [statsmodels]
   ------------- -------------------------- 1/3 [statsmodels]
   ------------- -------------------------- 1/3 [statsmodels]
   ------------- -------------------------- 1/3 [statsmodels]
   ------------- -------------------------- 1/3 [statsmodels]
   ------------- -------------------------- 1/3 [statsmodels]
   ------------- -------------------------- 1/3 [statsmodels]
   ------------- -------------------------- 1/3 [statsmodels]
   ------------- -------------------------- 1/3 [statsmodels]
   ------------- -------------------------- 1/3 [statsmodels]
   ------------- -------------------------- 1/3 [statsmodels]
   ------------- -------------------------- 1/3 [statsmodels]
   ------------- -------------------------- 1/3 [statsmodels]
   ------------- -------------------------- 1/3 [statsmodels]
   ------------- -------------------------- 1/3 [statsmodels]
   ------------- -------------------------- 1/3 [statsmodels]
   ------------- -------------------------- 1/3 [statsmodels]
   ------------- -------------------------- 1/3 [statsmodels]
   ------------- -------------------------- 1/3 [statsmodels]
   ------------- -------------------------- 1/3 [statsmodels]
   ------------- -------------------------- 1/3 [statsmodels]
   ------------- -------------------------- 1/3 [statsmodels]
   ------------- -------------------------- 1/3 [statsmodels]
   ------------- -------------------------- 1/3 [statsmodels]
   ------------- -------------------------- 1/3 [statsmodels]
   ------------- -------------------------- 1/3 [statsmodels]
   ------------- -------------------------- 1/3 [statsmodels]
   ------------- -------------------------- 1/3 [statsmodels]
   ------------- -------------------------- 1/3 [statsmodels]
   ------------- -------------------------- 1/3 [statsmodels]
   ------------- -------------------------- 1/3 [statsmodels]
   ------------- -------------------------- 1/3 [statsmodels]
   ------------- -------------------------- 1/3 [statsmodels]
   ------------- -------------------------- 1/3 [statsmodels]
   ------------- -------------------------- 1/3 [statsmodels]
   ------------- -------------------------- 1/3 [statsmodels]
   ------------- -------------------------- 1/3 [statsmodels]
   ------------- -------------------------- 1/3 [statsmodels]
   ------------- -------------------------- 1/3 [statsmodels]
   ------------- -------------------------- 1/3 [statsmodels]
   ------------- -------------------------- 1/3 [statsmodels]
   ------------- -------------------------- 1/3 [statsmodels]
   ------------- -------------------------- 1/3 [statsmodels]
   ------------- -------------------------- 1/3 [statsmodels]
   ------------- -------------------------- 1/3 [statsmodels]
   ------------- -------------------------- 1/3 [statsmodels]
   ------------- -------------------------- 1/3 [statsmodels]
   ------------- -------------------------- 1/3 [statsmodels]
   ------------- -------------------------- 1/3 [statsmodels]
   ------------- -------------------------- 1/3 [statsmodels]
   ------------- -------------------------- 1/3 [statsmodels]
   ------------- -------------------------- 1/3 [statsmodels]
   ------------- -------------------------- 1/3 [statsmodels]
   ------------- -------------------------- 1/3 [statsmodels]
   ------------- -------------------------- 1/3 [statsmodels]
   ------------- -------------------------- 1/3 [statsmodels]
   ------------- -------------------------- 1/3 [statsmodels]
   ------------- -------------------------- 1/3 [statsmodels]
   ------------- -------------------------- 1/3 [statsmodels]
   -------------------------- ------------- 2/3 [category_encoders]
   -------------------------- ------------- 2/3 [category_encoders]
   -------------------------- ------------- 2/3 [category_encoders]
   ---------------------------------------- 3/3 [category_encoders]

Successfully installed category_encoders-2.9.0 patsy-1.0.2 statsmodels-0.14.6

In [42]:
from category_encoders import BinaryEncoder

In [55]:
be=BinaryEncoder(cols=['city','product_category'])

In [60]:
df_copy=be.fit_transform(df)
df_copy.iloc[:,4:]

,employment_status,city_0,city_1,city_2,city_3,city_4,city_5,product_category_0,product_category_1,product_category_2,...,purchase_frequency,customer_segment,income_bracket,age_group,membership_status,preferred_language,region,season_joined,credit_rating,target_purchased
0,Full-time,0,0,0,0,0,1,0,0,1,...,Weekly,High Value,High,Adult,Gold,English,West,Summer,Excellent,Yes
1,Self-employed,0,0,0,0,1,0,0,1,0,...,Monthly,Medium Value,Medium,Senior,Silver,Hindi,North,Winter,Good,Yes
2,Unemployed,0,0,0,0,1,1,0,1,1,...,Rarely,Low Value,Low,Young Adult,Bronze,English,South,Spring,Fair,No
3,Full-time,0,0,0,1,0,0,1,0,0,...,Daily,High Value,Very High,Adult,Platinum,Telugu,South,Autumn,Excellent,Yes
4,Part-time,0,0,0,1,0,1,1,0,1,...,Weekly,Medium Value,Medium,Adult,Gold,Tamil,South,Summer,Good,Yes
5,Student,0,0,0,1,1,0,1,1,0,...,Monthly,Low Value,Low,Young Adult,Bronze,Bengali,East,Winter,Fair,No
6,Full-time,0,0,0,1,1,1,0,0,1,...,Weekly,High Value,High,Senior,Platinum,English,West,Spring,Excellent,Yes
7,Full-time,0,0,1,0,0,0,0,1,0,...,Bi-weekly,Medium Value,Medium,Adult,Silver,Gujarati,West,Autumn,Good,Yes
8,Unemployed,0,0,1,0,0,1,0,1,1,...,Rarely,Low Value,Low,Adult,Bronze,Hindi,North,Summer,Fair,No
9,Full-time,0,0,1,0,1,0,1,0,0,...,Daily,High Value,Very High,Senior,Platinum,Gujarati,West,Winter,Excellent,Yes
10,Part-time,0,0,1,0,1,1,1,0,1,...,Monthly,Low Value,Low,Young Adult,Bronze,Hindi,North,Spring,Poor,No
11,Full-time,0,0,1,1,0,0,1,1,0,...,Weekly,Medium Value,Medium,Adult,Gold,Hindi,North,Autumn,Good,Yes
12,Self-employed,0,0,1,1,0,1,0,0,1,...,Weekly,High Value,High,Senior,Platinum,Marathi,Central,Summer,Excellent,Yes
13,Full-time,0,0,1,1,1,0,0,1,0,...,Bi-weekly,Medium Value,Medium,Adult,Silver,Hindi,Central,Winter,Good,Yes
14,Full-time,0,0,1,1,1,1,0,1,1,...,Weekly,High Value,Very High,Senior,Platinum,Marathi,West,Spring,Excellent,Yes
15,Unemployed,0,1,0,0,0,0,1,0,0,...,Rarely,Low Value,Low,Young Adult,Bronze,Hindi,Central,Autumn,Fair,No
16,Part-time,0,1,0,0,0,1,1,0,1,...,Monthly,Medium Value,Medium,Adult,Gold,Telugu,South,Summer,Good,Yes
17,Full-time,0,1,0,0,1,0,1,1,0,...,Weekly,High Value,High,Senior,Platinum,Hindi,East,Winter,Excellent,Yes
18,Self-employed,0,1,0,0,1,1,0,0,1,...,Bi-weekly,Medium Value,Medium,Adult,Silver,Gujarati,West,Spring,Good,Yes
19,Student,0,1,0,1,0,0,0,1,0,...,Rarely,Low Value,Low,Young Adult,Bronze,Hindi,North,Autumn,Fair,No
20,Full-time,0,1,0,1,0,1,0,1,1,...,Daily,High Value,Very High,Senior,Platinum,Punjabi,North,Summer,Excellent,Yes
21,Unemployed,0,1,0,1,1,0,1,0,0,...,Monthly,Low Value,Low,Young Adult,Bronze,Hindi,North,Winter,Poor,No
22,Full-time,0,1,0,1,1,1,1,0,1,...,Weekly,Medium Value,Medium,Adult,Gold,Marathi,West,Spring,Good,Yes
23,Self-employed,0,1,1,0,0,0,1,1,0,...,Weekly,High Value,High,Senior,Platinum,Hindi,North,Autumn,Excellent,Yes
24,Part-time,0,1,1,0,0,1,0,0,1,...,Bi-weekly,Medium Value,Medium,Adult,Silver,Hindi,North,Summer,Good,Yes
25,Full-time,0,1,1,0,1,0,0,1,0,...,Weekly,High Value,Very High,Senior,Platinum,Gujarati,West,Winter,Excellent,Yes
26,Student,0,1,1,0,1,1,0,1,1,...,Rarely,Low Value,Low,Young Adult,Bronze,Marathi,West,Spring,Fair,No
27,Full-time,0,1,1,1,0,0,1,0,0,...,Monthly,Medium Value,Medium,Adult,Gold,Marathi,West,Autumn,Good,Yes
28,Full-time,0,1,1,1,0,1,1,0,1,...,Weekly,High Value,High,Senior,Platinum,Hindi,North,Summer,Excellent,Yes
29,Unemployed,0,1,1,1,1,0,1,1,0,...,Rarely,Low Value,Low,Adult,Bronze,Kashmiri,North,Winter,Fair,No
30,Full-time,0,1,1,1,1,1,0,0,1,...,Daily,High Value,Very High,Senior,Platinum,Marathi,Central,Spring,Excellent,Yes
31,Part-time,1,0,0,0,0,0,0,1,0,...,Monthly,Low Value,Low,Young Adult,Bronze,Hindi,East,Autumn,Poor,No
32,Full-time,1,0,0,0,0,1,0,1,1,...,Weekly,Medium Value,Medium,Adult,Gold,Punjabi,North,Summer,Good,Yes
33,Self-employed,1,0,0,0,1,0,1,0,0,...,Weekly,High Value,High,Senior,Platinum,Hindi,North,Winter,Excellent,Yes
34,Full-time,1,0,0,0,1,1,1,0,1,...,Bi-weekly,Medium Value,Medium,Adult,Silver,Hindi,East,Spring,Good,Yes
35,Part-time,1,0,0,1,0,0,1,1,0,...,Monthly,Medium Value,Medium,Adult,Gold,Bengali,East,Autumn,Good,Yes
36,Full-time,1,0,0,1,0,1,0,0,1,...,Weekly,High Value,Very High,Senior,Platinum,Tamil,South,Summer,Excellent,Yes
37,Unemployed,1,0,0,1,1,0,0,1,0,...,Rarely,Low Value,Low,Young Adult,Bronze,Hindi,North,Winter,Fair,No
38,Full-time,1,0,0,1,1,1,0,1,1,...,Weekly,High Value,High,Senior,Platinum,Tamil,South,Spring,Excellent,Yes
39,Self-employed,1,0,1,0,0,0,1,0,0,...,Daily,High Value,Very High,Senior,Platinum,Hindi,Central,Autumn,Excellent,Yes
40,Student,1,0,1,0,0,1,1,0,1,...,Monthly,Low Value,Low,Young Adult,Bronze,Telugu,South,Summer,Fair,No
41,Full-time,1,0,1,0,1,0,1,1,0,...,Weekly,Medium Value,Medium,Adult,Gold,Hindi,Central,Winter,Good,Yes
42,Part-time,1,0,1,0,1,1,0,0,1,...,Bi-weekly,Medium Value,Medium,Adult,Silver,Hindi,North,Spring,Good,Yes
43,Full-time,1,0,1,1,0,0,0,1,0,...,Weekly,High Value,High,Senior,Platinum,Kannada,South,Autumn,Excellent,Yes
44,Unemployed,1,0,1,1,0,1,0,1,1,...,Rarely,Low Value,Low,Young Adult,Bronze,Hindi,North,Summer,Poor,No
45,Full-time,1,0,1,1,1,0,1,0,0,...,Monthly,Medium Value,Medium,Adult,Gold,Hindi,North,Winter,Good,Yes
46,Self-employed,1,0,1,1,1,1,1,0,1,...,Weekly,High Value,Very High,Senior,Platinum,Hindi,North,Spring,Excellent,Yes
47,Full-time,1,1,0,0,0,0,1,1,0,...,Bi-weekly,Medium Value,Medium,Adult,Silver,Hindi,North,Autumn,Good,Yes
48,Full-time,1,1,0,0,0,1,0,0,1,...,Weekly,High Value,High,Senior,Platinum,Odia,East,Summer,Excellent,Yes
49,Student,1,1,0,0,1,0,0,1,0,...,Rarely,Low Value,Low,Young Adult,Bronze,Hindi,North,Winter,Fair,No

In [ ]:
for i in df_copy.columns:
    print(df_copy[i].unique())

In [54]:
df_copy

,education_level,employment_status,city_0,city_1,city_2,city_3,city_4,city_5,product_category,satisfaction_rating,...,age_group,membership_status,preferred_language,region,season_joined,credit_rating,target_purchased,gender_Female,gender_Male,Membership_Status
0,2,Full-time,0,0,0,0,0,1,Electronics,Very Satisfied,...,Adult,Gold,English,West,Summer,Excellent,Yes,1.0,0.0,2.0
1,3,Self-employed,0,0,0,0,1,0,Clothing,Satisfied,...,Senior,Silver,Hindi,North,Winter,Good,Yes,0.0,1.0,1.0
2,1,Unemployed,0,0,0,0,1,1,Home & Kitchen,Neutral,...,Young Adult,Bronze,English,South,Spring,Fair,No,0.0,1.0,0.0
3,4,Full-time,0,0,0,1,0,0,Beauty,Very Satisfied,...,Adult,Platinum,Telugu,South,Autumn,Excellent,Yes,1.0,0.0,3.0
4,2,Part-time,0,0,0,1,0,1,Sports,Satisfied,...,Adult,Gold,Tamil,South,Summer,Good,Yes,0.0,1.0,2.0
5,1,Student,0,0,0,1,1,0,Books,Dissatisfied,...,Young Adult,Bronze,Bengali,East,Winter,Fair,No,1.0,0.0,0.0
6,3,Full-time,0,0,0,1,1,1,Electronics,Very Satisfied,...,Senior,Platinum,English,West,Spring,Excellent,Yes,0.0,1.0,3.0
7,2,Full-time,0,0,1,0,0,0,Clothing,Satisfied,...,Adult,Silver,Gujarati,West,Autumn,Good,Yes,1.0,0.0,1.0
8,5,Unemployed,0,0,1,0,0,1,Home & Kitchen,Neutral,...,Adult,Bronze,Hindi,North,Summer,Fair,No,0.0,1.0,0.0
9,4,Full-time,0,0,1,0,1,0,Beauty,Very Satisfied,...,Senior,Platinum,Gujarati,West,Winter,Excellent,Yes,1.0,0.0,3.0
10,1,Part-time,0,0,1,0,1,1,Sports,Dissatisfied,...,Young Adult,Bronze,Hindi,North,Spring,Poor,No,0.0,1.0,0.0
11,2,Full-time,0,0,1,1,0,0,Books,Satisfied,...,Adult,Gold,Hindi,North,Autumn,Good,Yes,1.0,0.0,2.0
12,3,Self-employed,0,0,1,1,0,1,Electronics,Very Satisfied,...,Senior,Platinum,Marathi,Central,Summer,Excellent,Yes,0.0,1.0,3.0
13,5,Full-time,0,0,1,1,1,0,Clothing,Satisfied,...,Adult,Silver,Hindi,Central,Winter,Good,Yes,1.0,0.0,1.0
14,4,Full-time,0,0,1,1,1,1,Home & Kitchen,Very Satisfied,...,Senior,Platinum,Marathi,West,Spring,Excellent,Yes,0.0,1.0,3.0
15,1,Unemployed,0,1,0,0,0,0,Beauty,Neutral,...,Young Adult,Bronze,Hindi,Central,Autumn,Fair,No,1.0,0.0,0.0
16,2,Part-time,0,1,0,0,0,1,Sports,Satisfied,...,Adult,Gold,Telugu,South,Summer,Good,Yes,0.0,1.0,2.0
17,3,Full-time,0,1,0,0,1,0,Books,Very Satisfied,...,Senior,Platinum,Hindi,East,Winter,Excellent,Yes,1.0,0.0,3.0
18,5,Self-employed,0,1,0,0,1,1,Electronics,Satisfied,...,Adult,Silver,Gujarati,West,Spring,Good,Yes,0.0,1.0,1.0
19,1,Student,0,1,0,1,0,0,Clothing,Dissatisfied,...,Young Adult,Bronze,Hindi,North,Autumn,Fair,No,1.0,0.0,0.0
20,4,Full-time,0,1,0,1,0,1,Home & Kitchen,Very Satisfied,...,Senior,Platinum,Punjabi,North,Summer,Excellent,Yes,1.0,0.0,3.0
21,1,Unemployed,0,1,0,1,1,0,Beauty,Neutral,...,Young Adult,Bronze,Hindi,North,Winter,Poor,No,0.0,1.0,0.0
22,2,Full-time,0,1,0,1,1,1,Sports,Satisfied,...,Adult,Gold,Marathi,West,Spring,Good,Yes,1.0,0.0,2.0
23,3,Self-employed,0,1,1,0,0,0,Books,Very Satisfied,...,Senior,Platinum,Hindi,North,Autumn,Excellent,Yes,0.0,1.0,3.0
24,5,Part-time,0,1,1,0,0,1,Electronics,Satisfied,...,Adult,Silver,Hindi,North,Summer,Good,Yes,1.0,0.0,1.0
25,4,Full-time,0,1,1,0,1,0,Clothing,Very Satisfied,...,Senior,Platinum,Gujarati,West,Winter,Excellent,Yes,0.0,1.0,3.0
26,1,Student,0,1,1,0,1,1,Home & Kitchen,Dissatisfied,...,Young Adult,Bronze,Marathi,West,Spring,Fair,No,1.0,0.0,0.0
27,2,Full-time,0,1,1,1,0,0,Beauty,Satisfied,...,Adult,Gold,Marathi,West,Autumn,Good,Yes,0.0,1.0,2.0
28,3,Full-time,0,1,1,1,0,1,Sports,Very Satisfied,...,Senior,Platinum,Hindi,North,Summer,Excellent,Yes,1.0,0.0,3.0
29,5,Unemployed,0,1,1,1,1,0,Books,Neutral,...,Adult,Bronze,Kashmiri,North,Winter,Fair,No,0.0,1.0,0.0
30,4,Full-time,0,1,1,1,1,1,Electronics,Very Satisfied,...,Senior,Platinum,Marathi,Central,Spring,Excellent,Yes,1.0,0.0,3.0
31,1,Part-time,1,0,0,0,0,0,Clothing,Dissatisfied,...,Young Adult,Bronze,Hindi,East,Autumn,Poor,No,0.0,1.0,0.0
32,2,Full-time,1,0,0,0,0,1,Home & Kitchen,Satisfied,...,Adult,Gold,Punjabi,North,Summer,Good,Yes,1.0,0.0,2.0
33,3,Self-employed,1,0,0,0,1,0,Beauty,Very Satisfied,...,Senior,Platinum,Hindi,North,Winter,Excellent,Yes,0.0,1.0,3.0
34,5,Full-time,1,0,0,0,1,1,Sports,Satisfied,...,Adult,Silver,Hindi,East,Spring,Good,Yes,1.0,0.0,1.0
35,2,Part-time,1,0,0,1,0,0,Books,Satisfied,...,Adult,Gold,Bengali,East,Autumn,Good,Yes,0.0,1.0,2.0
36,4,Full-time,1,0,0,1,0,1,Electronics,Very Satisfied,...,Senior,Platinum,Tamil,South,Summer,Excellent,Yes,1.0,0.0,3.0
37,1,Unemployed,1,0,0,1,1,0,Clothing,Neutral,...,Young Adult,Bronze,Hindi,North,Winter,Fair,No,0.0,1.0,0.0
38,3,Full-time,1,0,0,1,1,1,Home & Kitchen,Very Satisfied,...,Senior,Platinum,Tamil,South,Spring,Excellent,Yes,1.0,0.0,3.0
39,4,Self-employed,1,0,1,0,0,0,Beauty,Very Satisfied,...,Senior,Platinum,Hindi,Central,Autumn,Excellent,Yes,0.0,1.0,3.0
40,1,Student,1,0,1,0,0,1,Sports,Dissatisfied,...,Young Adult,Bronze,Telugu,South,Summer,Fair,No,1.0,0.0,0.0
41,2,Full-time,1,0,1,0,1,0,Books,Satisfied,...,Adult,Gold,Hindi,Central,Winter,Good,Yes,0.0,1.0,2.0
42,5,Part-time,1,0,1,0,1,1,Electronics,Satisfied,...,Adult,Silver,Hindi,North,Spring,Good,Yes,1.0,0.0,1.0
43,3,Full-time,1,0,1,1,0,0,Clothing,Very Satisfied,...,Senior,Platinum,Kannada,South,Autumn,Excellent,Yes,1.0,0.0,3.0
44,1,Unemployed,1,0,1,1,0,1,Home & Kitchen,Neutral,...,Young Adult,Bronze,Hindi,North,Summer,Poor,No,0.0,1.0,0.0
45,2,Full-time,1,0,1,1,1,0,Beauty,Satisfied,...,Adult,Gold,Hindi,North,Winter,Good,Yes,1.0,0.0,2.0
46,4,Self-employed,1,0,1,1,1,1,Sports,Very Satisfied,...,Senior,Platinum,Hindi,North,Spring,Excellent,Yes,0.0,1.0,3.0
47,5,Full-time,1,1,0,0,0,0,Books,Satisfied,...,Adult,Silver,Hindi,North,Autumn,Good,Yes,1.0,0.0,1.0
48,3,Full-time,1,1,0,0,0,1,Electronics,Very Satisfied,...,Senior,Platinum,Odia,East,Summer,Excellent,Yes,0.0,1.0,3.0
49,1,Student,1,1,0,0,1,0,Clothing,Dissatisfied,...,Young Adult,Bronze,Hindi,North,Winter,Fair,No,1.0,0.0,0.0

In [62]:
df=pd.read_csv('data.csv')
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 50 entries, 0 to 49
Data columns (total 21 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   customer_id          50 non-null     int64
 1   name                 50 non-null     object
 2   gender               50 non-null     object
 3   education_level      50 non-null     object
 4   employment_status    50 non-null     object
 5   city                 50 non-null     object
 6   product_category     50 non-null     object
 7   satisfaction_rating  50 non-null     object
 8   subscription_tier    50 non-null     object
 9   payment_method       50 non-null     object
 10  device_type          50 non-null     object
 11  purchase_frequency   50 non-null     object
 12  customer_segment     50 non-null     object
 13  income_bracket       50 non-null     object
 14  age_group            50 non-null     object
 15  membership_status    50 non-null     object
 16  preferred_language   50 non-null     object
 17  region               50 non-null     object
 18  season_joined        50 non-null     object
 19  credit_rating        50 non-null     object
 20  target_purchased     50 non-null     object
dtypes: int64(1), object(20)
memory usage: 8.3+ KB

In [63]:
df_copy.to_csv('encoded.csv')