# Pandas Quick Tour for AI Engineers

it contains dataframes and series

In [3]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [51]:
!pip install seaborn

Requirement already satisfied: seaborn in c:\users\krivi\appdata\local\programs\python\python311\lib\site-packages (0.13.2)
Requirement already satisfied: numpy!=1.24.0,>=1.20 in c:\users\krivi\appdata\local\programs\python\python311\lib\site-packages (from seaborn) (2.3.5)
Requirement already satisfied: pandas>=1.2 in c:\users\krivi\appdata\local\programs\python\python311\lib\site-packages (from seaborn) (2.3.3)
Requirement already satisfied: matplotlib!=3.6.1,>=3.4 in c:\users\krivi\appdata\local\programs\python\python311\lib\site-packages (from seaborn) (3.10.7)
Requirement already satisfied: contourpy>=1.0.1 in c:\users\krivi\appdata\local\programs\python\python311\lib\site-packages (from matplotlib!=3.6.1,>=3.4->seaborn) (1.3.3)
Requirement already satisfied: cycler>=0.10 in c:\users\krivi\appdata\local\programs\python\python311\lib\site-packages (from matplotlib!=3.6.1,>=3.4->seaborn) (0.12.1)
Requirement already satisfied: fonttools>=4.22.0 in c:\users\krivi\appdata\local\programs\python\python311\lib\site-packages (from matplotlib!=3.6.1,>=3.4->seaborn) (4.61.0)
Requirement already satisfied: kiwisolver>=1.3.1 in c:\users\krivi\appdata\local\programs\python\python311\lib\site-packages (from matplotlib!=3.6.1,>=3.4->seaborn) (1.4.9)
Requirement already satisfied: packaging>=20.0 in c:\users\krivi\appdata\local\programs\python\python311\lib\site-packages (from matplotlib!=3.6.1,>=3.4->seaborn) (25.0)
Requirement already satisfied: pillow>=8 in c:\users\krivi\appdata\local\programs\python\python311\lib\site-packages (from matplotlib!=3.6.1,>=3.4->seaborn) (12.0.0)
Requirement already satisfied: pyparsing>=3 in c:\users\krivi\appdata\local\programs\python\python311\lib\site-packages (from matplotlib!=3.6.1,>=3.4->seaborn) (3.2.5)
Requirement already satisfied: python-dateutil>=2.7 in c:\users\krivi\appdata\local\programs\python\python311\lib\site-packages (from matplotlib!=3.6.1,>=3.4->seaborn) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in c:\users\krivi\appdata\local\programs\python\python311\lib\site-packages (from pandas>=1.2->seaborn) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in c:\users\krivi\appdata\local\programs\python\python311\lib\site-packages (from pandas>=1.2->seaborn) (2025.2)
Requirement already satisfied: six>=1.5 in c:\users\krivi\appdata\local\programs\python\python311\lib\site-packages (from python-dateutil>=2.7->matplotlib!=3.6.1,>=3.4->seaborn) (1.17.0)

In [52]:
import seaborn as sns

In [54]:
help(sns.load_dataset)

Help on function load_dataset in module seaborn.utils:

load_dataset(name, cache=True, data_home=None, **kws)
    Load an example dataset from the online repository (requires internet).

    This function provides quick access to a small number of example datasets
    that are useful for documenting seaborn or generating reproducible examples
    for bug reports. It is not necessary for normal usage.

    Note that some of the datasets have a small amount of preprocessing applied
    to define a proper ordering for categorical variables.

    Use :func:`get_dataset_names` to see a list of available datasets.

    Parameters
    ----------
    name : str
        Name of the dataset (``{name}.csv`` on
        https://github.com/mwaskom/seaborn-data).
    cache : boolean, optional
        If True, try to load from the local cache first, and save to the cache
        if a download is required.
    data_home : string, optional
        The directory in which to cache data; see :func:`get_data_home`.
    kws : keys and values, optional
        Additional keyword arguments are passed to passed through to
        :func:`pandas.read_csv`.

    Returns
    -------
    df : :class:`pandas.DataFrame`
        Tabular data, possibly with some preprocessing applied.

     total_bill   tip     sex smoker   day    time  size
0         16.99  1.01  Female     No   Sun  Dinner     2
1         10.34  1.66    Male     No   Sun  Dinner     3
2         21.01  3.50    Male     No   Sun  Dinner     3
3         23.68  3.31    Male     No   Sun  Dinner     2
4         24.59  3.61  Female     No   Sun  Dinner     4
..          ...   ...     ...    ...   ...     ...   ...
239       29.03  5.92    Male     No   Sat  Dinner     3
240       27.18  2.00  Female    Yes   Sat  Dinner     2
241       22.67  2.00    Male    Yes   Sat  Dinner     2
242       17.82  1.75    Male     No   Sat  Dinner     2
243       18.78  3.00  Female     No  Thur  Dinner     2

[244 rows x 7 columns]

In [2]:
!pip install pandas

Collecting pandas
  Downloading pandas-2.3.3-cp311-cp311-win_amd64.whl.metadata (19 kB)
Requirement already satisfied: numpy>=1.23.2 in c:\users\krivi\appdata\local\programs\python\python311\lib\site-packages (from pandas) (2.3.5)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\users\krivi\appdata\local\programs\python\python311\lib\site-packages (from pandas) (2.9.0.post0)
Collecting pytz>=2020.1 (from pandas)
  Downloading pytz-2025.2-py2.py3-none-any.whl.metadata (22 kB)
Requirement already satisfied: tzdata>=2022.7 in c:\users\krivi\appdata\local\programs\python\python311\lib\site-packages (from pandas) (2025.2)
Requirement already satisfied: six>=1.5 in c:\users\krivi\appdata\local\programs\python\python311\lib\site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Downloading pandas-2.3.3-cp311-cp311-win_amd64.whl (11.3 MB)
   ---------------------------------------- 0.0/11.3 MB ? eta -:--:--
   --------- ------------------------------ 2.6/11.3 MB 18.9 MB/s eta 0:00:01
   ---------------- ----------------------- 4.7/11.3 MB 12.4 MB/s eta 0:00:01
   -------------------- ------------------- 5.8/11.3 MB 10.1 MB/s eta 0:00:01
   ----------------------- ---------------- 6.6/11.3 MB 8.9 MB/s eta 0:00:01
   ------------------------ --------------- 6.8/11.3 MB 7.8 MB/s eta 0:00:01
   ------------------------ --------------- 7.1/11.3 MB 6.3 MB/s eta 0:00:01
   -------------------------- ------------- 7.6/11.3 MB 5.4 MB/s eta 0:00:01
   ---------------------------- ----------- 8.1/11.3 MB 5.0 MB/s eta 0:00:01
   ------------------------------ --------- 8.7/11.3 MB 4.8 MB/s eta 0:00:01
   -------------------------------- ------- 9.2/11.3 MB 4.6 MB/s eta 0:00:01
   ----------------------------------- ---- 10.0/11.3 MB 4.6 MB/s eta 0:00:01
   ------------------------------------ --- 10.5/11.3 MB 4.4 MB/s eta 0:00:01
   -------------------------------------- - 11.0/11.3 MB 4.2 MB/s eta 0:00:01
   ---------------------------------------- 11.3/11.3 MB 4.1 MB/s  0:00:02
Downloading pytz-2025.2-py2.py3-none-any.whl (509 kB)
Installing collected packages: pytz, pandas

   ---------------------------------------- 0/2 [pytz]
   ---------------------------------------- 0/2 [pytz]
   ---------------------------------------- 0/2 [pytz]
   ---------------------------------------- 0/2 [pytz]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   ---------------------------------------- 2/2 [pandas]

Successfully installed pandas-2.3.3 pytz-2025.2

In [16]:
data=["Mahender","vivek","hema","Python"]
s1=pd.Series(data)
s1.dtype #'o-object'

dtype('O')

In [9]:
s1[1:]

1     vivek
2      hema
3    Python
dtype: object

In [10]:
s1

0    Mahender
1       vivek
2        hema
3      Python
dtype: object

In [15]:

s1=pd.Series(np.arange(1,11))#1d
s1

0     1
1     2
2     3
3     4
4     5
5     6
6     7
7     8
8     9
9    10
dtype: int64

In [13]:
type(s1)

pandas.core.series.Series

In [14]:
s1.dtype

dtype('int64')

In [18]:
data={'name':['Ana','Bob'],
      'age':[25,30]}
df = pd.DataFrame(data) # it is a 2d array
print('DataFrame:\n', df)

DataFrame:
   name  age
0  Ana   25
1  Bob   30

In [45]:
data={
  "name": ["Arun", "Sneha", "Rohit", "Lavanya", "Kiran", "Pooja", "Manoj", "Divya", "Suresh", "Anitha"],
  "Age": [25, 28, 22, 30, 27, 23, 32, 26, 29, 24],
  "marks": [78, 85, 67, 90, 72, 88, 81, 76, 94, None]# this is float bec in pandas null value is treated as float
}

In [46]:
df=pd.DataFrame(data)

In [47]:
# info => null and datatype
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   name    10 non-null     object
 1   Age     10 non-null     int64
 2   marks   9 non-null      float64
dtypes: float64(1), int64(1), object(1)
memory usage: 368.0+ bytes

In [49]:
df

      name  Age  marks
0     Arun   25   78.0
1    Sneha   28   85.0
2    Rohit   22   67.0
3  Lavanya   30   90.0
4    Kiran   27   72.0
5    Pooja   23   88.0
6    Manoj   32   81.0
7    Divya   26   76.0
8   Suresh   29   94.0
9   Anitha   24    NaN

In [55]:
df2=sns.load_dataset('tips')

In [57]:
df2.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 244 entries, 0 to 243
Data columns (total 7 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   total_bill  244 non-null    float64
 1   tip         244 non-null    float64
 2   sex         244 non-null    category
 3   smoker      244 non-null    category
 4   day         244 non-null    category
 5   time        244 non-null    category
 6   size        244 non-null    int64
dtypes: category(4), float64(2), int64(1)
memory usage: 7.4 KB

In [60]:
df2.head()# 5records

   total_bill   tip     sex smoker  day    time  size
0       16.99  1.01  Female     No  Sun  Dinner     2
1       10.34  1.66    Male     No  Sun  Dinner     3
2       21.01  3.50    Male     No  Sun  Dinner     3
3       23.68  3.31    Male     No  Sun  Dinner     2
4       24.59  3.61  Female     No  Sun  Dinner     4

In [61]:
n=10
df2.head(n)# nrecords

   total_bill   tip     sex smoker  day    time  size
0       16.99  1.01  Female     No  Sun  Dinner     2
1       10.34  1.66    Male     No  Sun  Dinner     3
2       21.01  3.50    Male     No  Sun  Dinner     3
3       23.68  3.31    Male     No  Sun  Dinner     2
4       24.59  3.61  Female     No  Sun  Dinner     4
5       25.29  4.71    Male     No  Sun  Dinner     4
6        8.77  2.00    Male     No  Sun  Dinner     2
7       26.88  3.12    Male     No  Sun  Dinner     4
8       15.04  1.96    Male     No  Sun  Dinner     2
9       14.78  3.23    Male     No  Sun  Dinner     2

In [62]:
df2.tail()

     total_bill   tip     sex smoker   day    time  size
239       29.03  5.92    Male     No   Sat  Dinner     3
240       27.18  2.00  Female    Yes   Sat  Dinner     2
241       22.67  2.00    Male    Yes   Sat  Dinner     2
242       17.82  1.75    Male     No   Sat  Dinner     2
243       18.78  3.00  Female     No  Thur  Dinner     2

In [63]:
n=10
df2.tail(n)

     total_bill   tip     sex smoker   day    time  size
234       15.53  3.00    Male    Yes   Sat  Dinner     2
235       10.07  1.25    Male     No   Sat  Dinner     2
236       12.60  1.00    Male    Yes   Sat  Dinner     2
237       32.83  1.17    Male    Yes   Sat  Dinner     2
238       35.83  4.67  Female     No   Sat  Dinner     3
239       29.03  5.92    Male     No   Sat  Dinner     3
240       27.18  2.00  Female    Yes   Sat  Dinner     2
241       22.67  2.00    Male    Yes   Sat  Dinner     2
242       17.82  1.75    Male     No   Sat  Dinner     2
243       18.78  3.00  Female     No  Thur  Dinner     2

In [67]:
type(df2)

pandas.core.frame.DataFrame

In [68]:
# accessing columns 
df2['total_bill']
# or
df2.total_bill

0      16.99
1      10.34
2      21.01
3      23.68
4      24.59
       ...
239    29.03
240    27.18
241    22.67
242    17.82
243    18.78
Name: total_bill, Length: 244, dtype: float64

In [66]:
type(df2['total_bill'])

pandas.core.series.Series

In [69]:
columns=['total_bill','smoker','tip']

In [71]:
df2[columns]

     total_bill smoker   tip
0         16.99     No  1.01
1         10.34     No  1.66
2         21.01     No  3.50
3         23.68     No  3.31
4         24.59     No  3.61
..          ...    ...   ...
239       29.03     No  5.92
240       27.18    Yes  2.00
241       22.67    Yes  2.00
242       17.82     No  1.75
243       18.78     No  3.00

[244 rows x 3 columns]

In [72]:
# df.loc[row,col]

df2.loc[:,'total_bill':'smoker']

     total_bill   tip     sex smoker
0         16.99  1.01  Female     No
1         10.34  1.66    Male     No
2         21.01  3.50    Male     No
3         23.68  3.31    Male     No
4         24.59  3.61  Female     No
..          ...   ...     ...    ...
239       29.03  5.92    Male     No
240       27.18  2.00  Female    Yes
241       22.67  2.00    Male    Yes
242       17.82  1.75    Male     No
243       18.78  3.00  Female     No

[244 rows x 4 columns]

In [82]:
df2.loc[0,]
df2.loc[0,:]

total_bill     16.99
tip             1.01
sex           Female
smoker            No
day              Sun
time          Dinner
size               2
Name: 0, dtype: object

In [79]:
df=df2

In [80]:
df

     total_bill   tip     sex smoker   day    time  size
0         16.99  1.01  Female     No   Sun  Dinner     2
1         10.34  1.66    Male     No   Sun  Dinner     3
2         21.01  3.50    Male     No   Sun  Dinner     3
3         23.68  3.31    Male     No   Sun  Dinner     2
4         24.59  3.61  Female     No   Sun  Dinner     4
..          ...   ...     ...    ...   ...     ...   ...
239       29.03  5.92    Male     No   Sat  Dinner     3
240       27.18  2.00  Female    Yes   Sat  Dinner     2
241       22.67  2.00    Male    Yes   Sat  Dinner     2
242       17.82  1.75    Male     No   Sat  Dinner     2
243       18.78  3.00  Female     No  Thur  Dinner     2

[244 rows x 7 columns]

In [83]:
df.iloc[1,1]

np.float64(1.66)

In [84]:
df.iloc[:,1]

0      1.01
1      1.66
2      3.50
3      3.31
4      3.61
       ...
239    5.92
240    2.00
241    2.00
242    1.75
243    3.00
Name: tip, Length: 244, dtype: float64

In [86]:
df.iloc[:,0:5]#

     total_bill   tip     sex smoker   day
0         16.99  1.01  Female     No   Sun
1         10.34  1.66    Male     No   Sun
2         21.01  3.50    Male     No   Sun
3         23.68  3.31    Male     No   Sun
4         24.59  3.61  Female     No   Sun
..          ...   ...     ...    ...   ...
239       29.03  5.92    Male     No   Sat
240       27.18  2.00  Female    Yes   Sat
241       22.67  2.00    Male    Yes   Sat
242       17.82  1.75    Male     No   Sat
243       18.78  3.00  Female     No  Thur

[244 rows x 5 columns]

In [89]:
df['smoker'].upper()# series

AttributeError: 'Series' object has no attribute 'upper'

In [92]:
updated_smoker_data=df['smoker'].str.upper()# created new series

In [94]:
df['smoker']=updated_smoker_data

In [95]:
df

     total_bill   tip     sex smoker   day    time  size
0         16.99  1.01  Female     NO   Sun  Dinner     2
1         10.34  1.66    Male     NO   Sun  Dinner     3
2         21.01  3.50    Male     NO   Sun  Dinner     3
3         23.68  3.31    Male     NO   Sun  Dinner     2
4         24.59  3.61  Female     NO   Sun  Dinner     4
..          ...   ...     ...    ...   ...     ...   ...
239       29.03  5.92    Male     NO   Sat  Dinner     3
240       27.18  2.00  Female    YES   Sat  Dinner     2
241       22.67  2.00    Male    YES   Sat  Dinner     2
242       17.82  1.75    Male     NO   Sat  Dinner     2
243       18.78  3.00  Female     NO  Thur  Dinner     2

[244 rows x 7 columns]

In [98]:
df.sex=df['sex'].map(lambda x:"F" if x=="Female" else "M")

In [99]:
df

     total_bill   tip sex smoker   day    time  size
0         16.99  1.01   F     NO   Sun  Dinner     2
1         10.34  1.66   M     NO   Sun  Dinner     3
2         21.01  3.50   M     NO   Sun  Dinner     3
3         23.68  3.31   M     NO   Sun  Dinner     2
4         24.59  3.61   F     NO   Sun  Dinner     4
..          ...   ...  ..    ...   ...     ...   ...
239       29.03  5.92   M     NO   Sat  Dinner     3
240       27.18  2.00   F    YES   Sat  Dinner     2
241       22.67  2.00   M    YES   Sat  Dinner     2
242       17.82  1.75   M     NO   Sat  Dinner     2
243       18.78  3.00   F     NO  Thur  Dinner     2

[244 rows x 7 columns]

In [101]:
df.total_bill=df.total_bill.astype(int)

In [105]:
df.tip.describe()

count    244.000000
mean       2.998279
std        1.383638
min        1.000000
25%        2.000000
50%        2.900000
75%        3.562500
max       10.000000
Name: tip, dtype: float64

In [111]:
q1=np.quantile(df.tip,0.25)
q2=np.quantile(df.tip,0.50)
q3=np.quantile(df.tip,0.75)

In [114]:
df['grade']=df.tip.map(lambda x: 'O' if x>q3 else 'A' if x<q3 and x>q2 else 'B' )

In [115]:
df

     total_bill   tip sex smoker   day    time  size grade
0            16  1.01   F     NO   Sun  Dinner     2     B
1            10  1.66   M     NO   Sun  Dinner     3     B
2            21  3.50   M     NO   Sun  Dinner     3     A
3            23  3.31   M     NO   Sun  Dinner     2     A
4            24  3.61   F     NO   Sun  Dinner     4     O
..          ...   ...  ..    ...   ...     ...   ...   ...
239          29  5.92   M     NO   Sat  Dinner     3     O
240          27  2.00   F    YES   Sat  Dinner     2     B
241          22  2.00   M    YES   Sat  Dinner     2     B
242          17  1.75   M     NO   Sat  Dinner     2     B
243          18  3.00   F     NO  Thur  Dinner     2     A

[244 rows x 8 columns]

In [116]:
## reading data -> loading data from diff file formats

In [117]:
import sqlite3

In [118]:
connection=sqlite3.connect("sample.db")

In [119]:
connection

In [129]:

query="""SELECT 1 FROM sqlite_master WHERE type="table" """
print(connection.execute(query))# sql table
df=pd.read_sql(query,connection)

<sqlite3.Cursor object at 0x000001946D981F40>

In [130]:
df

   1
0  1

In [131]:
df

   1
0  1

In [132]:
df2=sns.load_dataset('tips')

In [133]:
df=df2

In [134]:
df # cleaned the data

     total_bill   tip     sex smoker   day    time  size
0         16.99  1.01  Female     No   Sun  Dinner     2
1         10.34  1.66    Male     No   Sun  Dinner     3
2         21.01  3.50    Male     No   Sun  Dinner     3
3         23.68  3.31    Male     No   Sun  Dinner     2
4         24.59  3.61  Female     No   Sun  Dinner     4
..          ...   ...     ...    ...   ...     ...   ...
239       29.03  5.92    Male     No   Sat  Dinner     3
240       27.18  2.00  Female    Yes   Sat  Dinner     2
241       22.67  2.00    Male    Yes   Sat  Dinner     2
242       17.82  1.75    Male     No   Sat  Dinner     2
243       18.78  3.00  Female     No  Thur  Dinner     2

[244 rows x 7 columns]

In [140]:
df.to_csv('data.csv')

In [188]:
df=pd.read_csv('data.csv')

In [189]:
df

,Unnamed: 0.1,Unnamed: 0,total_bill,tip,sex,smoker,day,time,size
0,0,0,16.99,1.01,Female,No,Sun,Dinner,2
1,1,1,10.34,1.66,Male,No,Sun,Dinner,3
2,2,2,21.01,3.50,Male,No,Sun,Dinner,3
3,3,3,23.68,3.31,Male,No,Sun,Dinner,2
4,4,4,24.59,3.61,Female,No,Sun,Dinner,4
...,...,...,...,...,...,...,...,...,...
239,239,239,29.03,5.92,Male,No,Sat,Dinner,3
240,240,240,27.18,2.00,Female,Yes,Sat,Dinner,2
241,241,241,22.67,2.00,Male,Yes,Sat,Dinner,2
242,242,242,17.82,1.75,Male,No,Sat,Dinner,2
243,243,243,18.78,3.00,Female,No,Thur,Dinner,2

In [190]:
df.to_json('data.json')

In [191]:
df=df.iloc[:,1:]

In [192]:
df.iloc[1:200:2,2:8:2]=None

In [193]:
# Nan=Not a number
df

     Unnamed: 0  total_bill   tip     sex smoker   day    time  size
0             0       16.99  1.01  Female     No   Sun  Dinner     2
1             1       10.34   NaN    Male   None   Sun    None     3
2             2       21.01  3.50    Male     No   Sun  Dinner     3
3             3       23.68   NaN    Male   None   Sun    None     2
4             4       24.59  3.61  Female     No   Sun  Dinner     4
..          ...         ...   ...     ...    ...   ...     ...   ...
239         239       29.03  5.92    Male     No   Sat  Dinner     3
240         240       27.18  2.00  Female    Yes   Sat  Dinner     2
241         241       22.67  2.00    Male    Yes   Sat  Dinner     2
242         242       17.82  1.75    Male     No   Sat  Dinner     2
243         243       18.78  3.00  Female     No  Thur  Dinner     2

[244 rows x 8 columns]

In [194]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 244 entries, 0 to 243
Data columns (total 8 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   Unnamed: 0  244 non-null    int64
 1   total_bill  244 non-null    float64
 2   tip         144 non-null    float64
 3   sex         244 non-null    object
 4   smoker      144 non-null    object
 5   day         244 non-null    object
 6   time        144 non-null    object
 7   size        244 non-null    int64
dtypes: float64(2), int64(2), object(4)
memory usage: 15.4+ KB

In [195]:
df

     Unnamed: 0  total_bill   tip     sex smoker   day    time  size
0             0       16.99  1.01  Female     No   Sun  Dinner     2
1             1       10.34   NaN    Male   None   Sun    None     3
2             2       21.01  3.50    Male     No   Sun  Dinner     3
3             3       23.68   NaN    Male   None   Sun    None     2
4             4       24.59  3.61  Female     No   Sun  Dinner     4
..          ...         ...   ...     ...    ...   ...     ...   ...
239         239       29.03  5.92    Male     No   Sat  Dinner     3
240         240       27.18  2.00  Female    Yes   Sat  Dinner     2
241         241       22.67  2.00    Male    Yes   Sat  Dinner     2
242         242       17.82  1.75    Male     No   Sat  Dinner     2
243         243       18.78  3.00  Female     No  Thur  Dinner     2

[244 rows x 8 columns]

In [196]:
df

     Unnamed: 0  total_bill   tip     sex smoker   day    time  size
0             0       16.99  1.01  Female     No   Sun  Dinner     2
1             1       10.34   NaN    Male   None   Sun    None     3
2             2       21.01  3.50    Male     No   Sun  Dinner     3
3             3       23.68   NaN    Male   None   Sun    None     2
4             4       24.59  3.61  Female     No   Sun  Dinner     4
..          ...         ...   ...     ...    ...   ...     ...   ...
239         239       29.03  5.92    Male     No   Sat  Dinner     3
240         240       27.18  2.00  Female    Yes   Sat  Dinner     2
241         241       22.67  2.00    Male    Yes   Sat  Dinner     2
242         242       17.82  1.75    Male     No   Sat  Dinner     2
243         243       18.78  3.00  Female     No  Thur  Dinner     2

[244 rows x 8 columns]

In [197]:
df

     Unnamed: 0  total_bill   tip     sex smoker   day    time  size
0             0       16.99  1.01  Female     No   Sun  Dinner     2
1             1       10.34   NaN    Male   None   Sun    None     3
2             2       21.01  3.50    Male     No   Sun  Dinner     3
3             3       23.68   NaN    Male   None   Sun    None     2
4             4       24.59  3.61  Female     No   Sun  Dinner     4
..          ...         ...   ...     ...    ...   ...     ...   ...
239         239       29.03  5.92    Male     No   Sat  Dinner     3
240         240       27.18  2.00  Female    Yes   Sat  Dinner     2
241         241       22.67  2.00    Male    Yes   Sat  Dinner     2
242         242       17.82  1.75    Male     No   Sat  Dinner     2
243         243       18.78  3.00  Female     No  Thur  Dinner     2

[244 rows x 8 columns]

In [198]:
df

     Unnamed: 0  total_bill   tip     sex smoker   day    time  size
0             0       16.99  1.01  Female     No   Sun  Dinner     2
1             1       10.34   NaN    Male   None   Sun    None     3
2             2       21.01  3.50    Male     No   Sun  Dinner     3
3             3       23.68   NaN    Male   None   Sun    None     2
4             4       24.59  3.61  Female     No   Sun  Dinner     4
..          ...         ...   ...     ...    ...   ...     ...   ...
239         239       29.03  5.92    Male     No   Sat  Dinner     3
240         240       27.18  2.00  Female    Yes   Sat  Dinner     2
241         241       22.67  2.00    Male    Yes   Sat  Dinner     2
242         242       17.82  1.75    Male     No   Sat  Dinner     2
243         243       18.78  3.00  Female     No  Thur  Dinner     2

[244 rows x 8 columns]

In [199]:
df

     Unnamed: 0  total_bill   tip     sex smoker   day    time  size
0             0       16.99  1.01  Female     No   Sun  Dinner     2
1             1       10.34   NaN    Male   None   Sun    None     3
2             2       21.01  3.50    Male     No   Sun  Dinner     3
3             3       23.68   NaN    Male   None   Sun    None     2
4             4       24.59  3.61  Female     No   Sun  Dinner     4
..          ...         ...   ...     ...    ...   ...     ...   ...
239         239       29.03  5.92    Male     No   Sat  Dinner     3
240         240       27.18  2.00  Female    Yes   Sat  Dinner     2
241         241       22.67  2.00    Male    Yes   Sat  Dinner     2
242         242       17.82  1.75    Male     No   Sat  Dinner     2
243         243       18.78  3.00  Female     No  Thur  Dinner     2

[244 rows x 8 columns]

In [200]:
df[df['size'].notnull()]

     Unnamed: 0  total_bill   tip     sex smoker   day    time  size
0             0       16.99  1.01  Female     No   Sun  Dinner     2
1             1       10.34   NaN    Male   None   Sun    None     3
2             2       21.01  3.50    Male     No   Sun  Dinner     3
3             3       23.68   NaN    Male   None   Sun    None     2
4             4       24.59  3.61  Female     No   Sun  Dinner     4
..          ...         ...   ...     ...    ...   ...     ...   ...
239         239       29.03  5.92    Male     No   Sat  Dinner     3
240         240       27.18  2.00  Female    Yes   Sat  Dinner     2
241         241       22.67  2.00    Male    Yes   Sat  Dinner     2
242         242       17.82  1.75    Male     No   Sat  Dinner     2
243         243       18.78  3.00  Female     No  Thur  Dinner     2

[244 rows x 8 columns]

In [201]:
# central tendency
# mean,mode,median

In [202]:
df['size'].describe()

count    244.000000
mean       2.569672
std        0.951100
min        1.000000
25%        2.000000
50%        2.000000
75%        3.000000
max        6.000000
Name: size, dtype: float64

In [203]:
mode=df['size'].mode()
mode

0    2
Name: size, dtype: int64

In [204]:
df['size']=df['size'].fillna(mode[0])

In [205]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 244 entries, 0 to 243
Data columns (total 8 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   Unnamed: 0  244 non-null    int64
 1   total_bill  244 non-null    float64
 2   tip         144 non-null    float64
 3   sex         244 non-null    object
 4   smoker      144 non-null    object
 5   day         244 non-null    object
 6   time        144 non-null    object
 7   size        244 non-null    int64
dtypes: float64(2), int64(2), object(4)
memory usage: 15.4+ KB

In [206]:
df[df.day.notnull()]

     Unnamed: 0  total_bill   tip     sex smoker   day    time  size
0             0       16.99  1.01  Female     No   Sun  Dinner     2
1             1       10.34   NaN    Male   None   Sun    None     3
2             2       21.01  3.50    Male     No   Sun  Dinner     3
3             3       23.68   NaN    Male   None   Sun    None     2
4             4       24.59  3.61  Female     No   Sun  Dinner     4
..          ...         ...   ...     ...    ...   ...     ...   ...
239         239       29.03  5.92    Male     No   Sat  Dinner     3
240         240       27.18  2.00  Female    Yes   Sat  Dinner     2
241         241       22.67  2.00    Male    Yes   Sat  Dinner     2
242         242       17.82  1.75    Male     No   Sat  Dinner     2
243         243       18.78  3.00  Female     No  Thur  Dinner     2

[244 rows x 8 columns]

In [207]:
df.day.mode()

0    Sat
Name: day, dtype: object

In [208]:
df.day.fillna('Sat',inplace=True)

C:\Users\krivi\AppData\Local\Temp\ipykernel_37624\3636855565.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df.day.fillna('Sat',inplace=True)

In [209]:
df

     Unnamed: 0  total_bill   tip     sex smoker   day    time  size
0             0       16.99  1.01  Female     No   Sun  Dinner     2
1             1       10.34   NaN    Male   None   Sun    None     3
2             2       21.01  3.50    Male     No   Sun  Dinner     3
3             3       23.68   NaN    Male   None   Sun    None     2
4             4       24.59  3.61  Female     No   Sun  Dinner     4
..          ...         ...   ...     ...    ...   ...     ...   ...
239         239       29.03  5.92    Male     No   Sat  Dinner     3
240         240       27.18  2.00  Female    Yes   Sat  Dinner     2
241         241       22.67  2.00    Male    Yes   Sat  Dinner     2
242         242       17.82  1.75    Male     No   Sat  Dinner     2
243         243       18.78  3.00  Female     No  Thur  Dinner     2

[244 rows x 8 columns]

In [210]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 244 entries, 0 to 243
Data columns (total 8 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   Unnamed: 0  244 non-null    int64
 1   total_bill  244 non-null    float64
 2   tip         144 non-null    float64
 3   sex         244 non-null    object
 4   smoker      144 non-null    object
 5   day         244 non-null    object
 6   time        144 non-null    object
 7   size        244 non-null    int64
dtypes: float64(2), int64(2), object(4)
memory usage: 15.4+ KB

In [1]:
import pandas as pd

In [7]:
df=pd.read_csv("C:/Users/krivi/OneDrive/Desktop/GEN-AI-NOV-2025/Data Wrangling & Visualization/data/missing.csv")

In [9]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 20 entries, 0 to 19
Data columns (total 10 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   id          20 non-null     int64
 1   name        20 non-null     object
 2   age         16 non-null     float64
 3   city        15 non-null     object
 4   salary      16 non-null     float64
 5   department  17 non-null     object
 6   experience  17 non-null     float64
 7   rating      16 non-null     float64
 8   join_date   17 non-null     object
 9   bonus       15 non-null     float64
dtypes: float64(5), int64(1), object(4)
memory usage: 1.7+ KB

In [10]:
df.describe()

             id        age        salary  experience     rating        bonus
count  20.00000  16.000000     16.000000   17.000000  16.000000    15.000000
mean   10.50000  30.000000  66875.000000    5.176471   4.250000  2980.000000
std     5.91608   4.320494  11982.626312    3.086975   0.368782  1374.356993
min     1.00000  24.000000  52000.000000    1.000000   3.700000  1200.000000
25%     5.75000  27.000000  58750.000000    3.000000   3.975000  2000.000000
50%    10.50000  29.000000  63000.000000    4.000000   4.200000  2700.000000
75%    15.25000  32.250000  72750.000000    7.000000   4.525000  3750.000000
max    20.00000  40.000000  90000.000000   12.000000   4.900000  6000.000000

In [12]:
df.age

0     25.0
1     30.0
2      NaN
3     28.0
4     32.0
5     29.0
6     27.0
7      NaN
8     26.0
9     35.0
10    31.0
11     NaN
12    24.0
13    29.0
14    33.0
15    40.0
16    28.0
17     NaN
18    27.0
19    36.0
Name: age, dtype: float64

In [15]:
df.age.mean()

np.float64(30.0)

In [17]:
df['age']=df['age'].fillna(df['age'].mean())

In [38]:
df=df.fillna({"salary":df.salary.mean(),'city':'Chicago','department':df.department.mode()[0],"experience":2,"join_date":"2021-05-10","rating":df.rating.mean(),'bonus':df.bonus.mode()[0]})

In [39]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 20 entries, 0 to 19
Data columns (total 10 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   id          20 non-null     int64
 1   name        20 non-null     object
 2   age         20 non-null     float64
 3   city        20 non-null     object
 4   salary      20 non-null     float64
 5   department  20 non-null     object
 6   experience  20 non-null     float64
 7   rating      20 non-null     float64
 8   join_date   20 non-null     object
 9   bonus       20 non-null     float64
dtypes: float64(5), int64(1), object(4)
memory usage: 1.7+ KB

In [43]:
df['join_date']=pd.to_datetime(df['join_date'])

In [ ]:
grouped_mean=df.groupby('department')['salary'].mean()
grouped_mean.inde

Index(['Finance', 'HR', 'IT', 'Sales'], dtype='object', name='department')

In [21]:
df.groupby('department')['salary'].min()

department
Finance    58000.0
HR         53000.0
IT         62000.0
Sales      52000.0
Name: salary, dtype: float64

In [22]:
df.groupby('department')['salary'].max()

department
Finance    83000.0
HR         90000.0
IT         88000.0
Sales      60000.0
Name: salary, dtype: float64

In [31]:
df.department.mode()[0]

'IT'

In [47]:
df.join_date[0]

Timestamp('2021-05-10 00:00:00')

In [49]:
df.age=df.age.astype(int)

In [50]:
df

,id,name,age,city,salary,department,experience,rating,join_date,bonus
0,1,Alice,25,New York,55000.0,Sales,2.0,4.50,2021-05-10,2000.0
1,2,Bob,30,Chicago,62000.0,IT,5.0,4.20,2020-03-15,3000.0
2,3,Charlie,30,Chicago,58000.0,Finance,3.0,4.25,2021-07-20,2500.0
3,4,David,28,San Francisco,66875.0,IT,4.0,3.90,2019-11-01,2000.0
4,5,Emma,32,Los Angeles,68000.0,IT,6.0,4.70,2022-01-05,3500.0
5,6,Frank,29,Houston,60000.0,Sales,2.0,4.00,2021-05-10,2800.0
6,7,Grace,27,Chicago,53000.0,HR,2.0,4.10,2021-02-18,2000.0
7,8,Harry,30,Dallas,75000.0,Finance,7.0,4.25,2020-12-25,4000.0
8,9,Ivy,26,Miami,66875.0,IT,1.0,3.80,2022-06-10,1500.0
9,10,Jack,35,New York,88000.0,IT,10.0,4.90,2021-05-10,5000.0
10,11,Karen,31,Chicago,61000.0,HR,5.0,4.30,2021-04-12,2700.0
11,12,Liam,30,Chicago,70000.0,IT,3.0,4.00,2022-03-09,2000.0
12,13,Mia,24,Seattle,52000.0,Sales,2.0,3.70,2023-01-15,1200.0
13,14,Noah,29,Houston,66875.0,Finance,4.0,4.25,2020-09-20,1800.0
14,15,Olivia,33,Chicago,72000.0,IT,8.0,4.60,2019-08-11,2000.0
15,16,Paul,40,Miami,90000.0,HR,12.0,4.80,2021-05-10,6000.0
16,17,Queen,28,Denver,66875.0,Sales,4.0,4.20,2021-10-05,2000.0
17,18,Ryan,30,Dallas,64000.0,IT,2.0,3.90,2020-04-17,2200.0
18,19,Sophia,27,Chicago,59000.0,IT,3.0,4.40,2021-06-01,2000.0
19,20,Tom,36,Chicago,83000.0,Finance,9.0,4.25,2020-01-10,4500.0

In [54]:
df.groupby(['city',"department"])['city'].count()

city           department
Chicago        Finance       2
               HR            2
               IT            4
Dallas         Finance       1
               IT            1
Denver         Sales         1
Houston        Finance       1
               Sales         1
Los Angeles    IT            1
Miami          HR            1
               IT            1
New York       IT            1
               Sales         1
San Francisco  IT            1
Seattle        Sales         1
Name: city, dtype: int64

In [55]:
df.groupby('department')['salary'].max()

department
Finance    83000.0
HR         90000.0
IT         88000.0
Sales      66875.0
Name: salary, dtype: float64

In [56]:
df.groupby('city')['salary'].max()

city
Chicago          83000.0
Dallas           75000.0
Denver           66875.0
Houston          66875.0
Los Angeles      68000.0
Miami            90000.0
New York         88000.0
San Francisco    66875.0
Seattle          52000.0
Name: salary, dtype: float64

In [59]:
df.groupby('city')['salary'].agg(['max','min','mean','count'])

                   max      min     mean  count
city
Chicago        83000.0  53000.0  64750.0      8
Dallas         75000.0  64000.0  69500.0      2
Denver         66875.0  66875.0  66875.0      1
Houston        66875.0  60000.0  63437.5      2
Los Angeles    68000.0  68000.0  68000.0      1
Miami          90000.0  66875.0  78437.5      2
New York       88000.0  55000.0  71500.0      2
San Francisco  66875.0  66875.0  66875.0      1
Seattle        52000.0  52000.0  52000.0      1

In [67]:
students=pd.read_csv("C:/Users/krivi/OneDrive/Desktop/GEN-AI-NOV-2025/Data Wrangling & Visualization/data/joins/students.csv")
students

   student_id student_name  department_id
0        S001        Alice              1
1        S002          Bob              2
2        S003      Charlie              3
3        S004        Diana              1
4        S005        Ethan              4
5        S006        Farah              2
6        S007       George              3
7        S008       Hannah              1
8        S009          Ian              4
9        S010        Jenny              2
10       S011        Karan              1
11       S012         Lisa              3
12       S013        Manoj              4
13       S014        Nisha              2
14       S015        Oscar              1
15       S016        Pooja              3
16       S017       Quincy              4
17       S018        Rahul              2
18       S019        Sneha              1
19       S020         Tony              3
20       S021          Uma              4
21       S022        Vijay              1
22       S023      Waheeda              2
23       S024       Xavier              3
24       S025       Yasmin              4

In [68]:
courses=pd.read_csv("C:/Users/krivi/OneDrive/Desktop/GEN-AI-NOV-2025/Data Wrangling & Visualization/data/joins/courses.csv")
courses

  course_id             course_name
0      C101         Data Structures
1      C102        Machine Learning
2      C103          Thermodynamics
3      C104         Fluid Mechanics
4      C105        Circuit Analysis
5      C106  Structural Engineering

In [69]:
enrollments=pd.read_csv("C:/Users/krivi/OneDrive/Desktop/GEN-AI-NOV-2025/Data Wrangling & Visualization/data/joins/enrollments.csv")
enrollments

   student_id course_id        date
0        S001      C101  2024-01-10
1        S002      C103  2024-01-12
2        S003      C106  2024-01-15
3        S004      C102  2024-01-18
4        S005      C105  2024-01-20
5        S006      C103  2024-01-22
6        S007      C106  2024-01-25
7        S008      C101  2024-01-28
8        S009      C105  2024-02-01
9        S010      C103  2024-02-03
10       S011      C101  2024-02-05
11       S012      C106  2024-02-08
12       S013      C105  2024-02-10
13       S014      C103  2024-02-12
14       S015      C102  2024-02-15
15       S016      C106  2024-02-18
16       S017      C105  2024-02-20
17       S018      C103  2024-02-22
18       S019      C102  2024-02-25
19       S020      C106  2024-02-27
20       S021      C105  2024-03-01
21       S022      C101  2024-03-03
22       S023      C103  2024-03-05
23       S024      C106  2024-03-08
24       S025      C105  2024-03-10

In [71]:
departments=pd.read_csv("C:/Users/krivi/OneDrive/Desktop/GEN-AI-NOV-2025/Data Wrangling & Visualization/data/joins/departments.csv")
departments

   department_id         department_name
0              1        Computer Science
1              2  Mechanical Engineering
2              3       Civil Engineering
3              4  Electrical Engineering

In [ ]:
students.head()

  student_id student_name  department_id
0       S001        Alice              1
1       S002          Bob              2
2       S003      Charlie              3
3       S004        Diana              1
4       S005        Ethan              4

In [74]:
departments.head()

   department_id         department_name
0              1        Computer Science
1              2  Mechanical Engineering
2              3       Civil Engineering
3              4  Electrical Engineering

In [78]:
pd.merge(students,departments,on="department_id",how='outer')

   student_id student_name  department_id         department_name
0        S001        Alice              1        Computer Science
1        S004        Diana              1        Computer Science
2        S008       Hannah              1        Computer Science
3        S011        Karan              1        Computer Science
4        S015        Oscar              1        Computer Science
5        S019        Sneha              1        Computer Science
6        S022        Vijay              1        Computer Science
7        S002          Bob              2  Mechanical Engineering
8        S006        Farah              2  Mechanical Engineering
9        S010        Jenny              2  Mechanical Engineering
10       S014        Nisha              2  Mechanical Engineering
11       S018        Rahul              2  Mechanical Engineering
12       S023      Waheeda              2  Mechanical Engineering
13       S003      Charlie              3       Civil Engineering
14       S007       George              3       Civil Engineering
15       S012         Lisa              3       Civil Engineering
16       S016        Pooja              3       Civil Engineering
17       S020         Tony              3       Civil Engineering
18       S024       Xavier              3       Civil Engineering
19       S005        Ethan              4  Electrical Engineering
20       S009          Ian              4  Electrical Engineering
21       S013        Manoj              4  Electrical Engineering
22       S017       Quincy              4  Electrical Engineering
23       S021          Uma              4  Electrical Engineering
24       S025       Yasmin              4  Electrical Engineering

In [84]:
df=students.merge(departments,on='department_id',how="inner").merge(enrollments,on="student_id").merge(courses,on='course_id')

In [85]:
df[['student_id',"student_name","department_name",'course_name','date']]

,student_id,student_name,department_name,course_name,date
0,S001,Alice,Computer Science,Data Structures,2024-01-10
1,S002,Bob,Mechanical Engineering,Thermodynamics,2024-01-12
2,S003,Charlie,Civil Engineering,Structural Engineering,2024-01-15
3,S004,Diana,Computer Science,Machine Learning,2024-01-18
4,S005,Ethan,Electrical Engineering,Circuit Analysis,2024-01-20
5,S006,Farah,Mechanical Engineering,Thermodynamics,2024-01-22
6,S007,George,Civil Engineering,Structural Engineering,2024-01-25
7,S008,Hannah,Computer Science,Data Structures,2024-01-28
8,S009,Ian,Electrical Engineering,Circuit Analysis,2024-02-01
9,S010,Jenny,Mechanical Engineering,Thermodynamics,2024-02-03
10,S011,Karan,Computer Science,Data Structures,2024-02-05
11,S012,Lisa,Civil Engineering,Structural Engineering,2024-02-08
12,S013,Manoj,Electrical Engineering,Circuit Analysis,2024-02-10
13,S014,Nisha,Mechanical Engineering,Thermodynamics,2024-02-12
14,S015,Oscar,Computer Science,Machine Learning,2024-02-15
15,S016,Pooja,Civil Engineering,Structural Engineering,2024-02-18
16,S017,Quincy,Electrical Engineering,Circuit Analysis,2024-02-20
17,S018,Rahul,Mechanical Engineering,Thermodynamics,2024-02-22
18,S019,Sneha,Computer Science,Machine Learning,2024-02-25
19,S020,Tony,Civil Engineering,Structural Engineering,2024-02-27
20,S021,Uma,Electrical Engineering,Circuit Analysis,2024-03-01
21,S022,Vijay,Computer Science,Data Structures,2024-03-03
22,S023,Waheeda,Mechanical Engineering,Thermodynamics,2024-03-05
23,S024,Xavier,Civil Engineering,Structural Engineering,2024-03-08
24,S025,Yasmin,Electrical Engineering,Circuit Analysis,2024-03-10