In [1]:
import pandas as pd
import numpy as np

In [2]:
df=pd.read_csv('data.csv')

In [3]:
df

,customer_id,session_duration,video_views,followers,registration_date,total_purchases,avg_order_value,last_login,account_balance,content_posted,membership_duration
0,1,2hr 30min,150K,2.5M,2020-03-15,45,2340.50,2024-12-10,125K,3hr 45min,4yr 9mo
1,2,1hr 45min,89K,1.2M,2021-06-22,23,1890.25,2024-12-08,55K,2hr 15min,3yr 6mo
2,3,3hr 20min,210K,5.8M,2019-11-08,67,3120.75,2024-12-11,245K,5hr 10min,5yr 1mo
3,4,45min,32K,450K,2023-01-30,12,980.00,2024-11-15,15K,1hr 5min,1yr 11mo
4,5,5hr 10min,310K,8.9M,2018-09-12,89,4250.30,2024-12-11,425K,6hr 30min,6yr 3mo
...,...,...,...,...,...,...,...,...,...,...,...
95,96,1hr 9min,69K,910K,2022-08-16,18,1130.80,2024-11-21,27.5K,1hr 36min,2yr 4mo
96,97,4hr 14min,254K,7.1M,2019-08-09,73,3680.90,2024-12-11,310K,5hr 49min,5yr 4mo
97,98,1hr 46min,106K,1.8M,2021-03-20,31,1630.70,2024-12-08,62K,2hr 29min,3yr 9mo
98,99,2hr 50min,170K,3.8M,2020-12-05,54,2690.50,2024-12-10,169K,4hr 6min,4yr 0mo
99,100,1hr 17min,76K,1.1M,2022-05-19,20,1200.60,2024-11-28,31.8K,1hr 49min,2yr 7mo

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 100 entries, 0 to 99
Data columns (total 11 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   customer_id          100 non-null    int64
 1   session_duration     100 non-null    object
 2   video_views          100 non-null    object
 3   followers            100 non-null    object
 4   registration_date    100 non-null    object
 5   total_purchases      100 non-null    int64
 6   avg_order_value      100 non-null    float64
 7   last_login           100 non-null    object
 8   account_balance      100 non-null    object
 9   content_posted       100 non-null    object
 10  membership_duration  100 non-null    object
dtypes: float64(1), int64(2), object(8)
memory usage: 8.7+ KB

In [5]:
df_copy=df.copy()

In [6]:
df_copy.session_duration.unique()

array(['2hr 30min', '1hr 45min', '3hr 20min', '45min', '5hr 10min',
       '1hr 52min', '2hr 58min', '1hr 7min', '4hr 27min', '1hr 35min',
       '2hr 14min', '52min', '3hr 18min', '1hr 43min', '2hr 42min',
       '1hr 11min', '4hr 5min', '1hr 28min', '2hr 28min', '1hr 18min',
       '4hr 49min', '1hr 58min', '3hr 5min', '48min', '4hr 16min',
       '1hr 38min', '2hr 19min', '1hr 3min', '3hr 43min', '1hr 47min',
       '2hr 49min', '1hr 14min', '4hr 31min', '1hr 24min', '2hr 35min',
       '58min', '3hr 58min', '1hr 32min', '2hr 22min', '1hr 21min',
       '4hr 38min', '1hr 54min', '3hr 1min', '1hr 9min', '4hr 9min',
       '1hr 41min', '2hr 31min', '1hr 12min', '4hr 25min', '1hr 33min',
       '2hr 17min', '54min', '3hr 50min', '1hr 36min', '2hr 39min',
       '1hr 1min', '4hr 13min', '1hr 30min', '2hr 26min', '1hr 16min',
       '4hr 43min', '1hr 56min', '3hr 8min', '56min', '4hr 21min',
       '1hr 39min', '2hr 21min', '1hr 13min', '4hr 2min', '2hr 46min',
       '1hr 8min', '4hr 35min', '1hr 34min', '2hr 29min', '1hr 15min',
       '4hr 18min', '1hr 49min', '2hr 52min', '1hr 2min', '4hr 46min',
       '2hr 0min', '3hr 14min', '4hr 28min', '1hr 37min', '2hr 23min',
       '1hr 19min', '4hr 32min', '1hr 42min', '2hr 43min', '4hr 26min',
       '1hr 29min', '2hr 32min', '4hr 14min', '1hr 46min', '2hr 50min',
       '1hr 17min'], dtype=object)

In [7]:
func=lambda x: '0hr '+x if 'hr' not in x else x
df_copy['session_duration']=df_copy['session_duration'].map(func)

In [8]:
df_copy['session_duration'].unique()

array(['2hr 30min', '1hr 45min', '3hr 20min', '0hr 45min', '5hr 10min',
       '1hr 52min', '2hr 58min', '1hr 7min', '4hr 27min', '1hr 35min',
       '2hr 14min', '0hr 52min', '3hr 18min', '1hr 43min', '2hr 42min',
       '1hr 11min', '4hr 5min', '1hr 28min', '2hr 28min', '1hr 18min',
       '4hr 49min', '1hr 58min', '3hr 5min', '0hr 48min', '4hr 16min',
       '1hr 38min', '2hr 19min', '1hr 3min', '3hr 43min', '1hr 47min',
       '2hr 49min', '1hr 14min', '4hr 31min', '1hr 24min', '2hr 35min',
       '0hr 58min', '3hr 58min', '1hr 32min', '2hr 22min', '1hr 21min',
       '4hr 38min', '1hr 54min', '3hr 1min', '1hr 9min', '4hr 9min',
       '1hr 41min', '2hr 31min', '1hr 12min', '4hr 25min', '1hr 33min',
       '2hr 17min', '0hr 54min', '3hr 50min', '1hr 36min', '2hr 39min',
       '1hr 1min', '4hr 13min', '1hr 30min', '2hr 26min', '1hr 16min',
       '4hr 43min', '1hr 56min', '3hr 8min', '0hr 56min', '4hr 21min',
       '1hr 39min', '2hr 21min', '1hr 13min', '4hr 2min', '2hr 46min',
       '1hr 8min', '4hr 35min', '1hr 34min', '2hr 29min', '1hr 15min',
       '4hr 18min', '1hr 49min', '2hr 52min', '1hr 2min', '4hr 46min',
       '2hr 0min', '3hr 14min', '4hr 28min', '1hr 37min', '2hr 23min',
       '1hr 19min', '4hr 32min', '1hr 42min', '2hr 43min', '4hr 26min',
       '1hr 29min', '2hr 32min', '4hr 14min', '1hr 46min', '2hr 50min',
       '1hr 17min'], dtype=object)

In [9]:
df_copy['session_duration']=(df_copy['session_duration'].str.split(" ").str[0].str[:-2].astype(int)*60) +(df_copy['session_duration'].str.split(" ").str[1].str[:-3].astype(int))

In [10]:
df_copy.rename(columns={'session_duration':'session_duration_mins'})

,customer_id,session_duration_mins,video_views,followers,registration_date,total_purchases,avg_order_value,last_login,account_balance,content_posted,membership_duration
0,1,150,150K,2.5M,2020-03-15,45,2340.50,2024-12-10,125K,3hr 45min,4yr 9mo
1,2,105,89K,1.2M,2021-06-22,23,1890.25,2024-12-08,55K,2hr 15min,3yr 6mo
2,3,200,210K,5.8M,2019-11-08,67,3120.75,2024-12-11,245K,5hr 10min,5yr 1mo
3,4,45,32K,450K,2023-01-30,12,980.00,2024-11-15,15K,1hr 5min,1yr 11mo
4,5,310,310K,8.9M,2018-09-12,89,4250.30,2024-12-11,425K,6hr 30min,6yr 3mo
...,...,...,...,...,...,...,...,...,...,...,...
95,96,69,69K,910K,2022-08-16,18,1130.80,2024-11-21,27.5K,1hr 36min,2yr 4mo
96,97,254,254K,7.1M,2019-08-09,73,3680.90,2024-12-11,310K,5hr 49min,5yr 4mo
97,98,106,106K,1.8M,2021-03-20,31,1630.70,2024-12-08,62K,2hr 29min,3yr 9mo
98,99,170,170K,3.8M,2020-12-05,54,2690.50,2024-12-10,169K,4hr 6min,4yr 0mo
99,100,77,76K,1.1M,2022-05-19,20,1200.60,2024-11-28,31.8K,1hr 49min,2yr 7mo

In [11]:
df_copy.video_views=df_copy.video_views.str[:-1].astype(int)

In [12]:
df_copy

,customer_id,session_duration,video_views,followers,registration_date,total_purchases,avg_order_value,last_login,account_balance,content_posted,membership_duration
0,1,150,150,2.5M,2020-03-15,45,2340.50,2024-12-10,125K,3hr 45min,4yr 9mo
1,2,105,89,1.2M,2021-06-22,23,1890.25,2024-12-08,55K,2hr 15min,3yr 6mo
2,3,200,210,5.8M,2019-11-08,67,3120.75,2024-12-11,245K,5hr 10min,5yr 1mo
3,4,45,32,450K,2023-01-30,12,980.00,2024-11-15,15K,1hr 5min,1yr 11mo
4,5,310,310,8.9M,2018-09-12,89,4250.30,2024-12-11,425K,6hr 30min,6yr 3mo
...,...,...,...,...,...,...,...,...,...,...,...
95,96,69,69,910K,2022-08-16,18,1130.80,2024-11-21,27.5K,1hr 36min,2yr 4mo
96,97,254,254,7.1M,2019-08-09,73,3680.90,2024-12-11,310K,5hr 49min,5yr 4mo
97,98,106,106,1.8M,2021-03-20,31,1630.70,2024-12-08,62K,2hr 29min,3yr 9mo
98,99,170,170,3.8M,2020-12-05,54,2690.50,2024-12-10,169K,4hr 6min,4yr 0mo
99,100,77,76,1.1M,2022-05-19,20,1200.60,2024-11-28,31.8K,1hr 49min,2yr 7mo

In [13]:
df.registration_date.unique()

array(['2020-03-15', '2021-06-22', '2019-11-08', '2023-01-30',
       '2018-09-12', '2021-07-25', '2020-05-03', '2022-08-17',
       '2019-02-14', '2021-10-27', '2020-11-19', '2022-03-22',
       '2019-05-11', '2021-07-08', '2020-01-16', '2022-04-29',
       '2019-09-13', '2021-06-05', '2020-11-20', '2022-02-18',
       '2019-05-07', '2021-10-14', '2020-12-03', '2022-09-28',
       '2019-07-15', '2021-01-09', '2020-08-22', '2022-12-17',
       '2019-04-25', '2021-03-19', '2020-06-08', '2022-10-02',
       '2019-02-24', '2021-09-03', '2020-05-21', '2022-12-29',
       '2019-06-18', '2021-03-27', '2020-07-09', '2022-10-15',
       '2019-01-28', '2021-11-22', '2020-05-17', '2022-08-09',
       '2019-12-11', '2021-02-24', '2020-10-13', '2022-05-06',
       '2019-08-27', '2021-02-22', '2020-04-07', '2022-09-07',
       '2019-03-17', '2021-08-09', '2020-02-27', '2022-11-25',
       '2019-10-21', '2021-07-14', '2020-04-19', '2022-12-11',
       '2019-12-23', '2021-05-03', '2020-10-28', '2022-02-16',
       '2019-06-13', '2021-10-20', '2020-03-22', '2022-05-09',
       '2019-09-30', '2021-07-23', '2020-12-02', '2022-06-10',
       '2019-11-03', '2021-04-01', '2020-09-25', '2022-11-18',
       '2019-12-26', '2021-05-06', '2020-08-18', '2022-11-03',
       '2019-05-15', '2021-08-07', '2020-12-08', '2022-04-02',
       '2019-08-25', '2021-12-18', '2020-06-10', '2022-03-01',
       '2019-06-23', '2021-10-08', '2020-11-30', '2022-06-23',
       '2019-04-07', '2021-10-16', '2020-01-23', '2022-08-16',
       '2019-08-09', '2021-03-20', '2020-12-05', '2022-05-19'],
      dtype=object)

In [14]:
df_copy.registration_date=pd.to_datetime(df_copy.registration_date)

In [15]:
df_copy.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 100 entries, 0 to 99
Data columns (total 11 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   customer_id          100 non-null    int64
 1   session_duration     100 non-null    int64
 2   video_views          100 non-null    int64
 3   followers            100 non-null    object
 4   registration_date    100 non-null    datetime64[ns]
 5   total_purchases      100 non-null    int64
 6   avg_order_value      100 non-null    float64
 7   last_login           100 non-null    object
 8   account_balance      100 non-null    object
 9   content_posted       100 non-null    object
 10  membership_duration  100 non-null    object
dtypes: datetime64[ns](1), float64(1), int64(4), object(5)
memory usage: 8.7+ KB

In [16]:
df_copy['registration_date']

0    2020-03-15
1    2021-06-22
2    2019-11-08
3    2023-01-30
4    2018-09-12
        ...
95   2022-08-16
96   2019-08-09
97   2021-03-20
98   2020-12-05
99   2022-05-19
Name: registration_date, Length: 100, dtype: datetime64[ns]

In [17]:

df_copy['registration_month']=df_copy['registration_date'].dt.month.astype(int)# attributes or varables
df_copy['registration_year']=df_copy['registration_date'].dt.year.astype(int)
df_copy['registration_date']=df_copy['registration_date'].dt.day.astype(int)

In [18]:
df_copy

,customer_id,session_duration,video_views,followers,registration_date,total_purchases,avg_order_value,last_login,account_balance,content_posted,membership_duration,registration_month,registration_year
0,1,150,150,2.5M,15,45,2340.50,2024-12-10,125K,3hr 45min,4yr 9mo,3,2020
1,2,105,89,1.2M,22,23,1890.25,2024-12-08,55K,2hr 15min,3yr 6mo,6,2021
2,3,200,210,5.8M,8,67,3120.75,2024-12-11,245K,5hr 10min,5yr 1mo,11,2019
3,4,45,32,450K,30,12,980.00,2024-11-15,15K,1hr 5min,1yr 11mo,1,2023
4,5,310,310,8.9M,12,89,4250.30,2024-12-11,425K,6hr 30min,6yr 3mo,9,2018
...,...,...,...,...,...,...,...,...,...,...,...,...,...
95,96,69,69,910K,16,18,1130.80,2024-11-21,27.5K,1hr 36min,2yr 4mo,8,2022
96,97,254,254,7.1M,9,73,3680.90,2024-12-11,310K,5hr 49min,5yr 4mo,8,2019
97,98,106,106,1.8M,20,31,1630.70,2024-12-08,62K,2hr 29min,3yr 9mo,3,2021
98,99,170,170,3.8M,5,54,2690.50,2024-12-10,169K,4hr 6min,4yr 0mo,12,2020
99,100,77,76,1.1M,19,20,1200.60,2024-11-28,31.8K,1hr 49min,2yr 7mo,5,2022

In [22]:
df_copy

,customer_id,session_duration,video_views,followers,registration_date,total_purchases,avg_order_value,last_login,account_balance,content_posted,membership_duration,registration_month,registration_year
0,1,150,150,2.5M,15,45,2340.50,2024-12-10,125K,3hr 45min,4yr 9mo,3,2020
1,2,105,89,1.2M,22,23,1890.25,2024-12-08,55K,2hr 15min,3yr 6mo,6,2021
2,3,200,210,5.8M,8,67,3120.75,2024-12-11,245K,5hr 10min,5yr 1mo,11,2019
3,4,45,32,450K,30,12,980.00,2024-11-15,15K,1hr 5min,1yr 11mo,1,2023
4,5,310,310,8.9M,12,89,4250.30,2024-12-11,425K,6hr 30min,6yr 3mo,9,2018
...,...,...,...,...,...,...,...,...,...,...,...,...,...
95,96,69,69,910K,16,18,1130.80,2024-11-21,27.5K,1hr 36min,2yr 4mo,8,2022
96,97,254,254,7.1M,9,73,3680.90,2024-12-11,310K,5hr 49min,5yr 4mo,8,2019
97,98,106,106,1.8M,20,31,1630.70,2024-12-08,62K,2hr 29min,3yr 9mo,3,2021
98,99,170,170,3.8M,5,54,2690.50,2024-12-10,169K,4hr 6min,4yr 0mo,12,2020
99,100,77,76,1.1M,19,20,1200.60,2024-11-28,31.8K,1hr 49min,2yr 7mo,5,2022

In [23]:
df_copy.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 100 entries, 0 to 99
Data columns (total 13 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   customer_id          100 non-null    int64
 1   session_duration     100 non-null    int64
 2   video_views          100 non-null    int64
 3   followers            100 non-null    object
 4   registration_date    100 non-null    int64
 5   total_purchases      100 non-null    int64
 6   avg_order_value      100 non-null    float64
 7   last_login           100 non-null    object
 8   account_balance      100 non-null    object
 9   content_posted       100 non-null    object
 10  membership_duration  100 non-null    object
 11  registration_month   100 non-null    int64
 12  registration_year    100 non-null    int64
dtypes: float64(1), int64(7), object(5)
memory usage: 10.3+ KB